// GENERATED FILE — do not edit by hand.
// Regenerate with: dart run ffigen --config ffigen.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Minimal FFI bindings for RAW decoding (not just thumbnails).
class LibRawBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibRawBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LibRawBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<libraw_data_t> libraw_init(int flags) {
    return _libraw_init(flags);
  }

  late final _libraw_initPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<libraw_data_t> Function(ffi.UnsignedInt)>
      >('libraw_init');
  late final _libraw_init = _libraw_initPtr
      .asFunction<ffi.Pointer<libraw_data_t> Function(int)>();

  int libraw_open_wfile(
    ffi.Pointer<libraw_data_t> arg0,
    ffi.Pointer<ffi.WChar> arg1,
  ) {
    return _libraw_open_wfile(arg0, arg1);
  }

  late final _libraw_open_wfilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<libraw_data_t>, ffi.Pointer<ffi.WChar>)
        >
      >('libraw_open_wfile');
  late final _libraw_open_wfile = _libraw_open_wfilePtr
      .asFunction<
        int Function(ffi.Pointer<libraw_data_t>, ffi.Pointer<ffi.WChar>)
      >();

  int libraw_open_file(
    ffi.Pointer<libraw_data_t> arg0,
    ffi.Pointer<ffi.Char> arg1,
  ) {
    return _libraw_open_file(arg0, arg1);
  }

  late final _libraw_open_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<libraw_data_t>, ffi.Pointer<ffi.Char>)
        >
      >('libraw_open_file');
  late final _libraw_open_file = _libraw_open_filePtr
      .asFunction<
        int Function(ffi.Pointer<libraw_data_t>, ffi.Pointer<ffi.Char>)
      >();

  int libraw_unpack(ffi.Pointer<libraw_data_t> arg0) {
    return _libraw_unpack(arg0);
  }

  late final _libraw_unpackPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<libraw_data_t>)>>(
        'libraw_unpack',
      );
  late final _libraw_unpack = _libraw_unpackPtr
      .asFunction<int Function(ffi.Pointer<libraw_data_t>)>();

  int libraw_unpack_thumb(ffi.Pointer<libraw_data_t> arg0) {
    return _libraw_unpack_thumb(arg0);
  }

  late final _libraw_unpack_thumbPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<libraw_data_t>)>>(
        'libraw_unpack_thumb',
      );
  late final _libraw_unpack_thumb = _libraw_unpack_thumbPtr
      .asFunction<int Function(ffi.Pointer<libraw_data_t>)>();

  int libraw_dcraw_process(ffi.Pointer<libraw_data_t> lr) {
    return _libraw_dcraw_process(lr);
  }

  late final _libraw_dcraw_processPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<libraw_data_t>)>>(
        'libraw_dcraw_process',
      );
  late final _libraw_dcraw_process = _libraw_dcraw_processPtr
      .asFunction<int Function(ffi.Pointer<libraw_data_t>)>();

  ffi.Pointer<libraw_processed_image_t> libraw_dcraw_make_mem_image(
    ffi.Pointer<libraw_data_t> lr,
    ffi.Pointer<ffi.Int> errc,
  ) {
    return _libraw_dcraw_make_mem_image(lr, errc);
  }

  late final _libraw_dcraw_make_mem_imagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<libraw_processed_image_t> Function(
            ffi.Pointer<libraw_data_t>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('libraw_dcraw_make_mem_image');
  late final _libraw_dcraw_make_mem_image = _libraw_dcraw_make_mem_imagePtr
      .asFunction<
        ffi.Pointer<libraw_processed_image_t> Function(
          ffi.Pointer<libraw_data_t>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  ffi.Pointer<libraw_processed_image_t> libraw_dcraw_make_mem_thumb(
    ffi.Pointer<libraw_data_t> lr,
    ffi.Pointer<ffi.Int> errc,
  ) {
    return _libraw_dcraw_make_mem_thumb(lr, errc);
  }

  late final _libraw_dcraw_make_mem_thumbPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<libraw_processed_image_t> Function(
            ffi.Pointer<libraw_data_t>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('libraw_dcraw_make_mem_thumb');
  late final _libraw_dcraw_make_mem_thumb = _libraw_dcraw_make_mem_thumbPtr
      .asFunction<
        ffi.Pointer<libraw_processed_image_t> Function(
          ffi.Pointer<libraw_data_t>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  void libraw_dcraw_clear_mem(ffi.Pointer<libraw_processed_image_t> arg0) {
    return _libraw_dcraw_clear_mem(arg0);
  }

  late final _libraw_dcraw_clear_memPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<libraw_processed_image_t>)
        >
      >('libraw_dcraw_clear_mem');
  late final _libraw_dcraw_clear_mem = _libraw_dcraw_clear_memPtr
      .asFunction<void Function(ffi.Pointer<libraw_processed_image_t>)>();

  void libraw_recycle(ffi.Pointer<libraw_data_t> arg0) {
    return _libraw_recycle(arg0);
  }

  late final _libraw_recyclePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<libraw_data_t>)>
      >('libraw_recycle');
  late final _libraw_recycle = _libraw_recyclePtr
      .asFunction<void Function(ffi.Pointer<libraw_data_t>)>();

  void libraw_close(ffi.Pointer<libraw_data_t> arg0) {
    return _libraw_close(arg0);
  }

  late final _libraw_closePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<libraw_data_t>)>
      >('libraw_close');
  late final _libraw_close = _libraw_closePtr
      .asFunction<void Function(ffi.Pointer<libraw_data_t>)>();

  ffi.Pointer<ffi.Char> libraw_strerror(int errorcode) {
    return _libraw_strerror(errorcode);
  }

  late final _libraw_strerrorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'libraw_strerror',
      );
  late final _libraw_strerror = _libraw_strerrorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();
}

enum LibRaw_open_flags {
  LIBRAW_OPEN_BIGFILE(1),
  LIBRAW_OPEN_FILE(2);

  final int value;
  const LibRaw_open_flags(this.value);

  static LibRaw_open_flags fromValue(int value) => switch (value) {
    1 => LIBRAW_OPEN_BIGFILE,
    2 => LIBRAW_OPEN_FILE,
    _ => throw ArgumentError('Unknown value for LibRaw_open_flags: $value'),
  };
}

enum LibRaw_openbayer_patterns {
  LIBRAW_OPENBAYER_RGGB(148),
  LIBRAW_OPENBAYER_BGGR(22),
  LIBRAW_OPENBAYER_GRBG(97),
  LIBRAW_OPENBAYER_GBRG(73);

  final int value;
  const LibRaw_openbayer_patterns(this.value);

  static LibRaw_openbayer_patterns fromValue(int value) => switch (value) {
    148 => LIBRAW_OPENBAYER_RGGB,
    22 => LIBRAW_OPENBAYER_BGGR,
    97 => LIBRAW_OPENBAYER_GRBG,
    73 => LIBRAW_OPENBAYER_GBRG,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_openbayer_patterns: $value',
    ),
  };
}

enum LibRaw_dngfields_marks {
  LIBRAW_DNGFM_FORWARDMATRIX(1),
  LIBRAW_DNGFM_ILLUMINANT(2),
  LIBRAW_DNGFM_COLORMATRIX(4),
  LIBRAW_DNGFM_CALIBRATION(8),
  LIBRAW_DNGFM_ANALOGBALANCE(16),
  LIBRAW_DNGFM_BLACK(32),
  LIBRAW_DNGFM_WHITE(64),
  LIBRAW_DNGFM_OPCODE2(128),
  LIBRAW_DNGFM_LINTABLE(256),
  LIBRAW_DNGFM_CROPORIGIN(512),
  LIBRAW_DNGFM_CROPSIZE(1024),
  LIBRAW_DNGFM_PREVIEWCS(2048),
  LIBRAW_DNGFM_ASSHOTNEUTRAL(4096),
  LIBRAW_DNGFM_BASELINEEXPOSURE(8192),
  LIBRAW_DNGFM_LINEARRESPONSELIMIT(16384),
  LIBRAW_DNGFM_USERCROP(32768),
  LIBRAW_DNGFM_OPCODE1(65536),
  LIBRAW_DNGFM_OPCODE3(131072);

  final int value;
  const LibRaw_dngfields_marks(this.value);

  static LibRaw_dngfields_marks fromValue(int value) => switch (value) {
    1 => LIBRAW_DNGFM_FORWARDMATRIX,
    2 => LIBRAW_DNGFM_ILLUMINANT,
    4 => LIBRAW_DNGFM_COLORMATRIX,
    8 => LIBRAW_DNGFM_CALIBRATION,
    16 => LIBRAW_DNGFM_ANALOGBALANCE,
    32 => LIBRAW_DNGFM_BLACK,
    64 => LIBRAW_DNGFM_WHITE,
    128 => LIBRAW_DNGFM_OPCODE2,
    256 => LIBRAW_DNGFM_LINTABLE,
    512 => LIBRAW_DNGFM_CROPORIGIN,
    1024 => LIBRAW_DNGFM_CROPSIZE,
    2048 => LIBRAW_DNGFM_PREVIEWCS,
    4096 => LIBRAW_DNGFM_ASSHOTNEUTRAL,
    8192 => LIBRAW_DNGFM_BASELINEEXPOSURE,
    16384 => LIBRAW_DNGFM_LINEARRESPONSELIMIT,
    32768 => LIBRAW_DNGFM_USERCROP,
    65536 => LIBRAW_DNGFM_OPCODE1,
    131072 => LIBRAW_DNGFM_OPCODE3,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_dngfields_marks: $value',
    ),
  };
}

enum LibRaw_As_Shot_WB_Applied_codes {
  LIBRAW_ASWB_APPLIED(1),
  LIBRAW_ASWB_CANON(2),
  LIBRAW_ASWB_NIKON(4),
  LIBRAW_ASWB_NIKON_SRAW(8),
  LIBRAW_ASWB_PENTAX(16),
  LIBRAW_ASWB_SONY(32);

  final int value;
  const LibRaw_As_Shot_WB_Applied_codes(this.value);

  static LibRaw_As_Shot_WB_Applied_codes fromValue(int value) =>
      switch (value) {
        1 => LIBRAW_ASWB_APPLIED,
        2 => LIBRAW_ASWB_CANON,
        4 => LIBRAW_ASWB_NIKON,
        8 => LIBRAW_ASWB_NIKON_SRAW,
        16 => LIBRAW_ASWB_PENTAX,
        32 => LIBRAW_ASWB_SONY,
        _ => throw ArgumentError(
          'Unknown value for LibRaw_As_Shot_WB_Applied_codes: $value',
        ),
      };
}

enum LibRaw_ExifTagTypes {
  LIBRAW_EXIFTAG_TYPE_UNKNOWN(0),
  LIBRAW_EXIFTAG_TYPE_BYTE(1),
  LIBRAW_EXIFTAG_TYPE_ASCII(2),
  LIBRAW_EXIFTAG_TYPE_SHORT(3),
  LIBRAW_EXIFTAG_TYPE_LONG(4),
  LIBRAW_EXIFTAG_TYPE_RATIONAL(5),
  LIBRAW_EXIFTAG_TYPE_SBYTE(6),
  LIBRAW_EXIFTAG_TYPE_UNDEFINED(7),
  LIBRAW_EXIFTAG_TYPE_SSHORT(8),
  LIBRAW_EXIFTAG_TYPE_SLONG(9),
  LIBRAW_EXIFTAG_TYPE_SRATIONAL(10),
  LIBRAW_EXIFTAG_TYPE_FLOAT(11),
  LIBRAW_EXIFTAG_TYPE_DOUBLE(12),
  LIBRAW_EXIFTAG_TYPE_IFD(13),
  LIBRAW_EXIFTAG_TYPE_UNICODE(14),
  LIBRAW_EXIFTAG_TYPE_COMPLEX(15),
  LIBRAW_EXIFTAG_TYPE_LONG8(16),
  LIBRAW_EXIFTAG_TYPE_SLONG8(17),
  LIBRAW_EXIFTAG_TYPE_IFD8(18);

  final int value;
  const LibRaw_ExifTagTypes(this.value);

  static LibRaw_ExifTagTypes fromValue(int value) => switch (value) {
    0 => LIBRAW_EXIFTAG_TYPE_UNKNOWN,
    1 => LIBRAW_EXIFTAG_TYPE_BYTE,
    2 => LIBRAW_EXIFTAG_TYPE_ASCII,
    3 => LIBRAW_EXIFTAG_TYPE_SHORT,
    4 => LIBRAW_EXIFTAG_TYPE_LONG,
    5 => LIBRAW_EXIFTAG_TYPE_RATIONAL,
    6 => LIBRAW_EXIFTAG_TYPE_SBYTE,
    7 => LIBRAW_EXIFTAG_TYPE_UNDEFINED,
    8 => LIBRAW_EXIFTAG_TYPE_SSHORT,
    9 => LIBRAW_EXIFTAG_TYPE_SLONG,
    10 => LIBRAW_EXIFTAG_TYPE_SRATIONAL,
    11 => LIBRAW_EXIFTAG_TYPE_FLOAT,
    12 => LIBRAW_EXIFTAG_TYPE_DOUBLE,
    13 => LIBRAW_EXIFTAG_TYPE_IFD,
    14 => LIBRAW_EXIFTAG_TYPE_UNICODE,
    15 => LIBRAW_EXIFTAG_TYPE_COMPLEX,
    16 => LIBRAW_EXIFTAG_TYPE_LONG8,
    17 => LIBRAW_EXIFTAG_TYPE_SLONG8,
    18 => LIBRAW_EXIFTAG_TYPE_IFD8,
    _ => throw ArgumentError('Unknown value for LibRaw_ExifTagTypes: $value'),
  };
}

enum LibRaw_whitebalance_code {
  LIBRAW_WBI_Unknown(0),
  LIBRAW_WBI_Daylight(1),
  LIBRAW_WBI_Fluorescent(2),
  LIBRAW_WBI_Tungsten(3),
  LIBRAW_WBI_Flash(4),
  LIBRAW_WBI_FineWeather(9),
  LIBRAW_WBI_Cloudy(10),
  LIBRAW_WBI_Shade(11),
  LIBRAW_WBI_FL_D(12),
  LIBRAW_WBI_FL_N(13),
  LIBRAW_WBI_FL_W(14),
  LIBRAW_WBI_FL_WW(15),
  LIBRAW_WBI_FL_L(16),
  LIBRAW_WBI_Ill_A(17),
  LIBRAW_WBI_Ill_B(18),
  LIBRAW_WBI_Ill_C(19),
  LIBRAW_WBI_D55(20),
  LIBRAW_WBI_D65(21),
  LIBRAW_WBI_D75(22),
  LIBRAW_WBI_D50(23),
  LIBRAW_WBI_StudioTungsten(24),
  LIBRAW_WBI_Sunset(64),
  LIBRAW_WBI_Underwater(65),
  LIBRAW_WBI_FluorescentHigh(66),
  LIBRAW_WBI_HT_Mercury(67),
  LIBRAW_WBI_AsShot(81),
  LIBRAW_WBI_Auto(82),
  LIBRAW_WBI_Custom(83),
  LIBRAW_WBI_Auto1(85),
  LIBRAW_WBI_Auto2(86),
  LIBRAW_WBI_Auto3(87),
  LIBRAW_WBI_Auto4(88),
  LIBRAW_WBI_Custom1(90),
  LIBRAW_WBI_Custom2(91),
  LIBRAW_WBI_Custom3(92),
  LIBRAW_WBI_Custom4(93),
  LIBRAW_WBI_Custom5(94),
  LIBRAW_WBI_Custom6(95),
  LIBRAW_WBI_PC_Set1(96),
  LIBRAW_WBI_PC_Set2(97),
  LIBRAW_WBI_PC_Set3(98),
  LIBRAW_WBI_PC_Set4(99),
  LIBRAW_WBI_PC_Set5(100),
  LIBRAW_WBI_Measured(110),
  LIBRAW_WBI_BW(120),
  LIBRAW_WBI_Kelvin(254),
  LIBRAW_WBI_Other(255),
  LIBRAW_WBI_None(65535);

  final int value;
  const LibRaw_whitebalance_code(this.value);

  static LibRaw_whitebalance_code fromValue(int value) => switch (value) {
    0 => LIBRAW_WBI_Unknown,
    1 => LIBRAW_WBI_Daylight,
    2 => LIBRAW_WBI_Fluorescent,
    3 => LIBRAW_WBI_Tungsten,
    4 => LIBRAW_WBI_Flash,
    9 => LIBRAW_WBI_FineWeather,
    10 => LIBRAW_WBI_Cloudy,
    11 => LIBRAW_WBI_Shade,
    12 => LIBRAW_WBI_FL_D,
    13 => LIBRAW_WBI_FL_N,
    14 => LIBRAW_WBI_FL_W,
    15 => LIBRAW_WBI_FL_WW,
    16 => LIBRAW_WBI_FL_L,
    17 => LIBRAW_WBI_Ill_A,
    18 => LIBRAW_WBI_Ill_B,
    19 => LIBRAW_WBI_Ill_C,
    20 => LIBRAW_WBI_D55,
    21 => LIBRAW_WBI_D65,
    22 => LIBRAW_WBI_D75,
    23 => LIBRAW_WBI_D50,
    24 => LIBRAW_WBI_StudioTungsten,
    64 => LIBRAW_WBI_Sunset,
    65 => LIBRAW_WBI_Underwater,
    66 => LIBRAW_WBI_FluorescentHigh,
    67 => LIBRAW_WBI_HT_Mercury,
    81 => LIBRAW_WBI_AsShot,
    82 => LIBRAW_WBI_Auto,
    83 => LIBRAW_WBI_Custom,
    85 => LIBRAW_WBI_Auto1,
    86 => LIBRAW_WBI_Auto2,
    87 => LIBRAW_WBI_Auto3,
    88 => LIBRAW_WBI_Auto4,
    90 => LIBRAW_WBI_Custom1,
    91 => LIBRAW_WBI_Custom2,
    92 => LIBRAW_WBI_Custom3,
    93 => LIBRAW_WBI_Custom4,
    94 => LIBRAW_WBI_Custom5,
    95 => LIBRAW_WBI_Custom6,
    96 => LIBRAW_WBI_PC_Set1,
    97 => LIBRAW_WBI_PC_Set2,
    98 => LIBRAW_WBI_PC_Set3,
    99 => LIBRAW_WBI_PC_Set4,
    100 => LIBRAW_WBI_PC_Set5,
    110 => LIBRAW_WBI_Measured,
    120 => LIBRAW_WBI_BW,
    254 => LIBRAW_WBI_Kelvin,
    255 => LIBRAW_WBI_Other,
    65535 => LIBRAW_WBI_None,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_whitebalance_code: $value',
    ),
  };
}

enum LibRaw_MultiExposure_related {
  LIBRAW_ME_NONE(0),
  LIBRAW_ME_SIMPLE(1),
  LIBRAW_ME_OVERLAY(2),
  LIBRAW_ME_HDR(3);

  final int value;
  const LibRaw_MultiExposure_related(this.value);

  static LibRaw_MultiExposure_related fromValue(int value) => switch (value) {
    0 => LIBRAW_ME_NONE,
    1 => LIBRAW_ME_SIMPLE,
    2 => LIBRAW_ME_OVERLAY,
    3 => LIBRAW_ME_HDR,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_MultiExposure_related: $value',
    ),
  };
}

enum LibRaw_dng_processing {
  LIBRAW_DNG_NONE(0),
  LIBRAW_DNG_FLOAT(1),
  LIBRAW_DNG_LINEAR(2),
  LIBRAW_DNG_DEFLATE(4),
  LIBRAW_DNG_XTRANS(8),
  LIBRAW_DNG_OTHER(16),
  LIBRAW_DNG_8BIT(32),
  LIBRAW_DNG_ALL(63),
  LIBRAW_DNG_DEFAULT(39);

  final int value;
  const LibRaw_dng_processing(this.value);

  static LibRaw_dng_processing fromValue(int value) => switch (value) {
    0 => LIBRAW_DNG_NONE,
    1 => LIBRAW_DNG_FLOAT,
    2 => LIBRAW_DNG_LINEAR,
    4 => LIBRAW_DNG_DEFLATE,
    8 => LIBRAW_DNG_XTRANS,
    16 => LIBRAW_DNG_OTHER,
    32 => LIBRAW_DNG_8BIT,
    63 => LIBRAW_DNG_ALL,
    39 => LIBRAW_DNG_DEFAULT,
    _ => throw ArgumentError('Unknown value for LibRaw_dng_processing: $value'),
  };
}

enum LibRaw_output_flags {
  LIBRAW_OUTPUT_FLAGS_NONE(0),
  LIBRAW_OUTPUT_FLAGS_PPMMETA(1);

  final int value;
  const LibRaw_output_flags(this.value);

  static LibRaw_output_flags fromValue(int value) => switch (value) {
    0 => LIBRAW_OUTPUT_FLAGS_NONE,
    1 => LIBRAW_OUTPUT_FLAGS_PPMMETA,
    _ => throw ArgumentError('Unknown value for LibRaw_output_flags: $value'),
  };
}

enum LibRaw_runtime_capabilities {
  LIBRAW_CAPS_RAWSPEED(1),
  LIBRAW_CAPS_DNGSDK(2),
  LIBRAW_CAPS_GPRSDK(4),
  LIBRAW_CAPS_UNICODEPATHS(8),
  LIBRAW_CAPS_X3FTOOLS(16),
  LIBRAW_CAPS_RPI6BY9(32),
  LIBRAW_CAPS_ZLIB(64),
  LIBRAW_CAPS_JPEG(128),
  LIBRAW_CAPS_RAWSPEED3(256),
  LIBRAW_CAPS_RAWSPEED_BITS(512);

  final int value;
  const LibRaw_runtime_capabilities(this.value);

  static LibRaw_runtime_capabilities fromValue(int value) => switch (value) {
    1 => LIBRAW_CAPS_RAWSPEED,
    2 => LIBRAW_CAPS_DNGSDK,
    4 => LIBRAW_CAPS_GPRSDK,
    8 => LIBRAW_CAPS_UNICODEPATHS,
    16 => LIBRAW_CAPS_X3FTOOLS,
    32 => LIBRAW_CAPS_RPI6BY9,
    64 => LIBRAW_CAPS_ZLIB,
    128 => LIBRAW_CAPS_JPEG,
    256 => LIBRAW_CAPS_RAWSPEED3,
    512 => LIBRAW_CAPS_RAWSPEED_BITS,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_runtime_capabilities: $value',
    ),
  };
}

enum LibRaw_colorspace {
  LIBRAW_COLORSPACE_NotFound(0),
  LIBRAW_COLORSPACE_sRGB(1),
  LIBRAW_COLORSPACE_AdobeRGB(2),
  LIBRAW_COLORSPACE_WideGamutRGB(3),
  LIBRAW_COLORSPACE_ProPhotoRGB(4),
  LIBRAW_COLORSPACE_ICC(5),
  LIBRAW_COLORSPACE_Uncalibrated(6),
  LIBRAW_COLORSPACE_CameraLinearUniWB(7),
  LIBRAW_COLORSPACE_CameraLinear(8),
  LIBRAW_COLORSPACE_CameraGammaUniWB(9),
  LIBRAW_COLORSPACE_CameraGamma(10),
  LIBRAW_COLORSPACE_MonochromeLinear(11),
  LIBRAW_COLORSPACE_MonochromeGamma(12),
  LIBRAW_COLORSPACE_Rec2020(13),
  LIBRAW_COLORSPACE_Unknown(255);

  final int value;
  const LibRaw_colorspace(this.value);

  static LibRaw_colorspace fromValue(int value) => switch (value) {
    0 => LIBRAW_COLORSPACE_NotFound,
    1 => LIBRAW_COLORSPACE_sRGB,
    2 => LIBRAW_COLORSPACE_AdobeRGB,
    3 => LIBRAW_COLORSPACE_WideGamutRGB,
    4 => LIBRAW_COLORSPACE_ProPhotoRGB,
    5 => LIBRAW_COLORSPACE_ICC,
    6 => LIBRAW_COLORSPACE_Uncalibrated,
    7 => LIBRAW_COLORSPACE_CameraLinearUniWB,
    8 => LIBRAW_COLORSPACE_CameraLinear,
    9 => LIBRAW_COLORSPACE_CameraGammaUniWB,
    10 => LIBRAW_COLORSPACE_CameraGamma,
    11 => LIBRAW_COLORSPACE_MonochromeLinear,
    12 => LIBRAW_COLORSPACE_MonochromeGamma,
    13 => LIBRAW_COLORSPACE_Rec2020,
    255 => LIBRAW_COLORSPACE_Unknown,
    _ => throw ArgumentError('Unknown value for LibRaw_colorspace: $value'),
  };
}

enum LibRaw_cameramaker_index {
  LIBRAW_CAMERAMAKER_Unknown(0),
  LIBRAW_CAMERAMAKER_Agfa(1),
  LIBRAW_CAMERAMAKER_Alcatel(2),
  LIBRAW_CAMERAMAKER_Apple(3),
  LIBRAW_CAMERAMAKER_Aptina(4),
  LIBRAW_CAMERAMAKER_AVT(5),
  LIBRAW_CAMERAMAKER_Baumer(6),
  LIBRAW_CAMERAMAKER_Broadcom(7),
  LIBRAW_CAMERAMAKER_Canon(8),
  LIBRAW_CAMERAMAKER_Casio(9),
  LIBRAW_CAMERAMAKER_CINE(10),
  LIBRAW_CAMERAMAKER_Clauss(11),
  LIBRAW_CAMERAMAKER_Contax(12),
  LIBRAW_CAMERAMAKER_Creative(13),
  LIBRAW_CAMERAMAKER_DJI(14),
  LIBRAW_CAMERAMAKER_DXO(15),
  LIBRAW_CAMERAMAKER_Epson(16),
  LIBRAW_CAMERAMAKER_Foculus(17),
  LIBRAW_CAMERAMAKER_Fujifilm(18),
  LIBRAW_CAMERAMAKER_Generic(19),
  LIBRAW_CAMERAMAKER_Gione(20),
  LIBRAW_CAMERAMAKER_GITUP(21),
  LIBRAW_CAMERAMAKER_Google(22),
  LIBRAW_CAMERAMAKER_GoPro(23),
  LIBRAW_CAMERAMAKER_Hasselblad(24),
  LIBRAW_CAMERAMAKER_HTC(25),
  LIBRAW_CAMERAMAKER_I_Mobile(26),
  LIBRAW_CAMERAMAKER_Imacon(27),
  LIBRAW_CAMERAMAKER_JK_Imaging(28),
  LIBRAW_CAMERAMAKER_Kodak(29),
  LIBRAW_CAMERAMAKER_Konica(30),
  LIBRAW_CAMERAMAKER_Leaf(31),
  LIBRAW_CAMERAMAKER_Leica(32),
  LIBRAW_CAMERAMAKER_Lenovo(33),
  LIBRAW_CAMERAMAKER_LG(34),
  LIBRAW_CAMERAMAKER_Logitech(35),
  LIBRAW_CAMERAMAKER_Mamiya(36),
  LIBRAW_CAMERAMAKER_Matrix(37),
  LIBRAW_CAMERAMAKER_Meizu(38),
  LIBRAW_CAMERAMAKER_Micron(39),
  LIBRAW_CAMERAMAKER_Minolta(40),
  LIBRAW_CAMERAMAKER_Motorola(41),
  LIBRAW_CAMERAMAKER_NGM(42),
  LIBRAW_CAMERAMAKER_Nikon(43),
  LIBRAW_CAMERAMAKER_Nokia(44),
  LIBRAW_CAMERAMAKER_Olympus(45),
  LIBRAW_CAMERAMAKER_OmniVison(46),
  LIBRAW_CAMERAMAKER_Panasonic(47),
  LIBRAW_CAMERAMAKER_Parrot(48),
  LIBRAW_CAMERAMAKER_Pentax(49),
  LIBRAW_CAMERAMAKER_PhaseOne(50),
  LIBRAW_CAMERAMAKER_PhotoControl(51),
  LIBRAW_CAMERAMAKER_Photron(52),
  LIBRAW_CAMERAMAKER_Pixelink(53),
  LIBRAW_CAMERAMAKER_Polaroid(54),
  LIBRAW_CAMERAMAKER_RED(55),
  LIBRAW_CAMERAMAKER_Ricoh(56),
  LIBRAW_CAMERAMAKER_Rollei(57),
  LIBRAW_CAMERAMAKER_RoverShot(58),
  LIBRAW_CAMERAMAKER_Samsung(59),
  LIBRAW_CAMERAMAKER_Sigma(60),
  LIBRAW_CAMERAMAKER_Sinar(61),
  LIBRAW_CAMERAMAKER_SMaL(62),
  LIBRAW_CAMERAMAKER_Sony(63),
  LIBRAW_CAMERAMAKER_ST_Micro(64),
  LIBRAW_CAMERAMAKER_THL(65),
  LIBRAW_CAMERAMAKER_VLUU(66),
  LIBRAW_CAMERAMAKER_Xiaomi(67),
  LIBRAW_CAMERAMAKER_XIAOYI(68),
  LIBRAW_CAMERAMAKER_YI(69),
  LIBRAW_CAMERAMAKER_Yuneec(70),
  LIBRAW_CAMERAMAKER_Zeiss(71),
  LIBRAW_CAMERAMAKER_OnePlus(72),
  LIBRAW_CAMERAMAKER_ISG(73),
  LIBRAW_CAMERAMAKER_VIVO(74),
  LIBRAW_CAMERAMAKER_HMD_Global(75),
  LIBRAW_CAMERAMAKER_HUAWEI(76),
  LIBRAW_CAMERAMAKER_RaspberryPi(77),
  LIBRAW_CAMERAMAKER_OmDigital(78),
  LIBRAW_CAMERAMAKER_TheLastOne(79);

  final int value;
  const LibRaw_cameramaker_index(this.value);

  static LibRaw_cameramaker_index fromValue(int value) => switch (value) {
    0 => LIBRAW_CAMERAMAKER_Unknown,
    1 => LIBRAW_CAMERAMAKER_Agfa,
    2 => LIBRAW_CAMERAMAKER_Alcatel,
    3 => LIBRAW_CAMERAMAKER_Apple,
    4 => LIBRAW_CAMERAMAKER_Aptina,
    5 => LIBRAW_CAMERAMAKER_AVT,
    6 => LIBRAW_CAMERAMAKER_Baumer,
    7 => LIBRAW_CAMERAMAKER_Broadcom,
    8 => LIBRAW_CAMERAMAKER_Canon,
    9 => LIBRAW_CAMERAMAKER_Casio,
    10 => LIBRAW_CAMERAMAKER_CINE,
    11 => LIBRAW_CAMERAMAKER_Clauss,
    12 => LIBRAW_CAMERAMAKER_Contax,
    13 => LIBRAW_CAMERAMAKER_Creative,
    14 => LIBRAW_CAMERAMAKER_DJI,
    15 => LIBRAW_CAMERAMAKER_DXO,
    16 => LIBRAW_CAMERAMAKER_Epson,
    17 => LIBRAW_CAMERAMAKER_Foculus,
    18 => LIBRAW_CAMERAMAKER_Fujifilm,
    19 => LIBRAW_CAMERAMAKER_Generic,
    20 => LIBRAW_CAMERAMAKER_Gione,
    21 => LIBRAW_CAMERAMAKER_GITUP,
    22 => LIBRAW_CAMERAMAKER_Google,
    23 => LIBRAW_CAMERAMAKER_GoPro,
    24 => LIBRAW_CAMERAMAKER_Hasselblad,
    25 => LIBRAW_CAMERAMAKER_HTC,
    26 => LIBRAW_CAMERAMAKER_I_Mobile,
    27 => LIBRAW_CAMERAMAKER_Imacon,
    28 => LIBRAW_CAMERAMAKER_JK_Imaging,
    29 => LIBRAW_CAMERAMAKER_Kodak,
    30 => LIBRAW_CAMERAMAKER_Konica,
    31 => LIBRAW_CAMERAMAKER_Leaf,
    32 => LIBRAW_CAMERAMAKER_Leica,
    33 => LIBRAW_CAMERAMAKER_Lenovo,
    34 => LIBRAW_CAMERAMAKER_LG,
    35 => LIBRAW_CAMERAMAKER_Logitech,
    36 => LIBRAW_CAMERAMAKER_Mamiya,
    37 => LIBRAW_CAMERAMAKER_Matrix,
    38 => LIBRAW_CAMERAMAKER_Meizu,
    39 => LIBRAW_CAMERAMAKER_Micron,
    40 => LIBRAW_CAMERAMAKER_Minolta,
    41 => LIBRAW_CAMERAMAKER_Motorola,
    42 => LIBRAW_CAMERAMAKER_NGM,
    43 => LIBRAW_CAMERAMAKER_Nikon,
    44 => LIBRAW_CAMERAMAKER_Nokia,
    45 => LIBRAW_CAMERAMAKER_Olympus,
    46 => LIBRAW_CAMERAMAKER_OmniVison,
    47 => LIBRAW_CAMERAMAKER_Panasonic,
    48 => LIBRAW_CAMERAMAKER_Parrot,
    49 => LIBRAW_CAMERAMAKER_Pentax,
    50 => LIBRAW_CAMERAMAKER_PhaseOne,
    51 => LIBRAW_CAMERAMAKER_PhotoControl,
    52 => LIBRAW_CAMERAMAKER_Photron,
    53 => LIBRAW_CAMERAMAKER_Pixelink,
    54 => LIBRAW_CAMERAMAKER_Polaroid,
    55 => LIBRAW_CAMERAMAKER_RED,
    56 => LIBRAW_CAMERAMAKER_Ricoh,
    57 => LIBRAW_CAMERAMAKER_Rollei,
    58 => LIBRAW_CAMERAMAKER_RoverShot,
    59 => LIBRAW_CAMERAMAKER_Samsung,
    60 => LIBRAW_CAMERAMAKER_Sigma,
    61 => LIBRAW_CAMERAMAKER_Sinar,
    62 => LIBRAW_CAMERAMAKER_SMaL,
    63 => LIBRAW_CAMERAMAKER_Sony,
    64 => LIBRAW_CAMERAMAKER_ST_Micro,
    65 => LIBRAW_CAMERAMAKER_THL,
    66 => LIBRAW_CAMERAMAKER_VLUU,
    67 => LIBRAW_CAMERAMAKER_Xiaomi,
    68 => LIBRAW_CAMERAMAKER_XIAOYI,
    69 => LIBRAW_CAMERAMAKER_YI,
    70 => LIBRAW_CAMERAMAKER_Yuneec,
    71 => LIBRAW_CAMERAMAKER_Zeiss,
    72 => LIBRAW_CAMERAMAKER_OnePlus,
    73 => LIBRAW_CAMERAMAKER_ISG,
    74 => LIBRAW_CAMERAMAKER_VIVO,
    75 => LIBRAW_CAMERAMAKER_HMD_Global,
    76 => LIBRAW_CAMERAMAKER_HUAWEI,
    77 => LIBRAW_CAMERAMAKER_RaspberryPi,
    78 => LIBRAW_CAMERAMAKER_OmDigital,
    79 => LIBRAW_CAMERAMAKER_TheLastOne,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_cameramaker_index: $value',
    ),
  };
}

enum LibRaw_camera_mounts {
  LIBRAW_MOUNT_Unknown(0),
  LIBRAW_MOUNT_Alpa(1),
  LIBRAW_MOUNT_C(2),
  LIBRAW_MOUNT_Canon_EF_M(3),
  LIBRAW_MOUNT_Canon_EF_S(4),
  LIBRAW_MOUNT_Canon_EF(5),
  LIBRAW_MOUNT_Canon_RF(6),
  LIBRAW_MOUNT_Contax_N(7),
  LIBRAW_MOUNT_Contax645(8),
  LIBRAW_MOUNT_FT(9),
  LIBRAW_MOUNT_mFT(10),
  LIBRAW_MOUNT_Fuji_GF(11),
  LIBRAW_MOUNT_Fuji_GX(12),
  LIBRAW_MOUNT_Fuji_X(13),
  LIBRAW_MOUNT_Hasselblad_H(14),
  LIBRAW_MOUNT_Hasselblad_V(15),
  LIBRAW_MOUNT_Hasselblad_XCD(16),
  LIBRAW_MOUNT_Leica_M(17),
  LIBRAW_MOUNT_Leica_R(18),
  LIBRAW_MOUNT_Leica_S(19),
  LIBRAW_MOUNT_Leica_SL(20),
  LIBRAW_MOUNT_Leica_TL(21),
  LIBRAW_MOUNT_LPS_L(22),
  LIBRAW_MOUNT_Mamiya67(23),
  LIBRAW_MOUNT_Mamiya645(24),
  LIBRAW_MOUNT_Minolta_A(25),
  LIBRAW_MOUNT_Nikon_CX(26),
  LIBRAW_MOUNT_Nikon_F(27),
  LIBRAW_MOUNT_Nikon_Z(28),
  LIBRAW_MOUNT_PhaseOne_iXM_MV(29),
  LIBRAW_MOUNT_PhaseOne_iXM_RS(30),
  LIBRAW_MOUNT_PhaseOne_iXM(31),
  LIBRAW_MOUNT_Pentax_645(32),
  LIBRAW_MOUNT_Pentax_K(33),
  LIBRAW_MOUNT_Pentax_Q(34),
  LIBRAW_MOUNT_RicohModule(35),
  LIBRAW_MOUNT_Rollei_bayonet(36),
  LIBRAW_MOUNT_Samsung_NX_M(37),
  LIBRAW_MOUNT_Samsung_NX(38),
  LIBRAW_MOUNT_Sigma_X3F(39),
  LIBRAW_MOUNT_Sony_E(40),
  LIBRAW_MOUNT_LF(41),
  LIBRAW_MOUNT_DigitalBack(42),
  LIBRAW_MOUNT_FixedLens(43),
  LIBRAW_MOUNT_IL_UM(44),
  LIBRAW_MOUNT_TheLastOne(45);

  final int value;
  const LibRaw_camera_mounts(this.value);

  static LibRaw_camera_mounts fromValue(int value) => switch (value) {
    0 => LIBRAW_MOUNT_Unknown,
    1 => LIBRAW_MOUNT_Alpa,
    2 => LIBRAW_MOUNT_C,
    3 => LIBRAW_MOUNT_Canon_EF_M,
    4 => LIBRAW_MOUNT_Canon_EF_S,
    5 => LIBRAW_MOUNT_Canon_EF,
    6 => LIBRAW_MOUNT_Canon_RF,
    7 => LIBRAW_MOUNT_Contax_N,
    8 => LIBRAW_MOUNT_Contax645,
    9 => LIBRAW_MOUNT_FT,
    10 => LIBRAW_MOUNT_mFT,
    11 => LIBRAW_MOUNT_Fuji_GF,
    12 => LIBRAW_MOUNT_Fuji_GX,
    13 => LIBRAW_MOUNT_Fuji_X,
    14 => LIBRAW_MOUNT_Hasselblad_H,
    15 => LIBRAW_MOUNT_Hasselblad_V,
    16 => LIBRAW_MOUNT_Hasselblad_XCD,
    17 => LIBRAW_MOUNT_Leica_M,
    18 => LIBRAW_MOUNT_Leica_R,
    19 => LIBRAW_MOUNT_Leica_S,
    20 => LIBRAW_MOUNT_Leica_SL,
    21 => LIBRAW_MOUNT_Leica_TL,
    22 => LIBRAW_MOUNT_LPS_L,
    23 => LIBRAW_MOUNT_Mamiya67,
    24 => LIBRAW_MOUNT_Mamiya645,
    25 => LIBRAW_MOUNT_Minolta_A,
    26 => LIBRAW_MOUNT_Nikon_CX,
    27 => LIBRAW_MOUNT_Nikon_F,
    28 => LIBRAW_MOUNT_Nikon_Z,
    29 => LIBRAW_MOUNT_PhaseOne_iXM_MV,
    30 => LIBRAW_MOUNT_PhaseOne_iXM_RS,
    31 => LIBRAW_MOUNT_PhaseOne_iXM,
    32 => LIBRAW_MOUNT_Pentax_645,
    33 => LIBRAW_MOUNT_Pentax_K,
    34 => LIBRAW_MOUNT_Pentax_Q,
    35 => LIBRAW_MOUNT_RicohModule,
    36 => LIBRAW_MOUNT_Rollei_bayonet,
    37 => LIBRAW_MOUNT_Samsung_NX_M,
    38 => LIBRAW_MOUNT_Samsung_NX,
    39 => LIBRAW_MOUNT_Sigma_X3F,
    40 => LIBRAW_MOUNT_Sony_E,
    41 => LIBRAW_MOUNT_LF,
    42 => LIBRAW_MOUNT_DigitalBack,
    43 => LIBRAW_MOUNT_FixedLens,
    44 => LIBRAW_MOUNT_IL_UM,
    45 => LIBRAW_MOUNT_TheLastOne,
    _ => throw ArgumentError('Unknown value for LibRaw_camera_mounts: $value'),
  };
}

enum LibRaw_camera_formats {
  LIBRAW_FORMAT_Unknown(0),
  LIBRAW_FORMAT_APSC(1),
  LIBRAW_FORMAT_FF(2),
  LIBRAW_FORMAT_MF(3),
  LIBRAW_FORMAT_APSH(4),
  LIBRAW_FORMAT_1INCH(5),
  LIBRAW_FORMAT_1div2p3INCH(6),
  LIBRAW_FORMAT_1div1p7INCH(7),
  LIBRAW_FORMAT_FT(8),
  LIBRAW_FORMAT_CROP645(9),
  LIBRAW_FORMAT_LeicaS(10),
  LIBRAW_FORMAT_645(11),
  LIBRAW_FORMAT_66(12),
  LIBRAW_FORMAT_69(13),
  LIBRAW_FORMAT_LF(14),
  LIBRAW_FORMAT_Leica_DMR(15),
  LIBRAW_FORMAT_67(16),
  LIBRAW_FORMAT_SigmaAPSC(17),
  LIBRAW_FORMAT_SigmaMerrill(18),
  LIBRAW_FORMAT_SigmaAPSH(19),
  LIBRAW_FORMAT_3648(20),
  LIBRAW_FORMAT_68(21),
  LIBRAW_FORMAT_TheLastOne(22);

  final int value;
  const LibRaw_camera_formats(this.value);

  static LibRaw_camera_formats fromValue(int value) => switch (value) {
    0 => LIBRAW_FORMAT_Unknown,
    1 => LIBRAW_FORMAT_APSC,
    2 => LIBRAW_FORMAT_FF,
    3 => LIBRAW_FORMAT_MF,
    4 => LIBRAW_FORMAT_APSH,
    5 => LIBRAW_FORMAT_1INCH,
    6 => LIBRAW_FORMAT_1div2p3INCH,
    7 => LIBRAW_FORMAT_1div1p7INCH,
    8 => LIBRAW_FORMAT_FT,
    9 => LIBRAW_FORMAT_CROP645,
    10 => LIBRAW_FORMAT_LeicaS,
    11 => LIBRAW_FORMAT_645,
    12 => LIBRAW_FORMAT_66,
    13 => LIBRAW_FORMAT_69,
    14 => LIBRAW_FORMAT_LF,
    15 => LIBRAW_FORMAT_Leica_DMR,
    16 => LIBRAW_FORMAT_67,
    17 => LIBRAW_FORMAT_SigmaAPSC,
    18 => LIBRAW_FORMAT_SigmaMerrill,
    19 => LIBRAW_FORMAT_SigmaAPSH,
    20 => LIBRAW_FORMAT_3648,
    21 => LIBRAW_FORMAT_68,
    22 => LIBRAW_FORMAT_TheLastOne,
    _ => throw ArgumentError('Unknown value for LibRaw_camera_formats: $value'),
  };
}

enum LibRaw_lens_focal_types {
  LIBRAW_FT_UNDEFINED(0),
  LIBRAW_FT_PRIME_LENS(1),
  LIBRAW_FT_ZOOM_LENS(2),
  LIBRAW_FT_ZOOM_LENS_CONSTANT_APERTURE(3),
  LIBRAW_FT_ZOOM_LENS_VARIABLE_APERTURE(4);

  final int value;
  const LibRaw_lens_focal_types(this.value);

  static LibRaw_lens_focal_types fromValue(int value) => switch (value) {
    0 => LIBRAW_FT_UNDEFINED,
    1 => LIBRAW_FT_PRIME_LENS,
    2 => LIBRAW_FT_ZOOM_LENS,
    3 => LIBRAW_FT_ZOOM_LENS_CONSTANT_APERTURE,
    4 => LIBRAW_FT_ZOOM_LENS_VARIABLE_APERTURE,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_lens_focal_types: $value',
    ),
  };
}

enum LibRaw_Canon_RecordModes {
  LIBRAW_Canon_RecordMode_UNDEFINED(0),
  LIBRAW_Canon_RecordMode_JPEG(1),
  LIBRAW_Canon_RecordMode_CRW_THM(2),
  LIBRAW_Canon_RecordMode_AVI_THM(3),
  LIBRAW_Canon_RecordMode_TIF(4),
  LIBRAW_Canon_RecordMode_TIF_JPEG(5),
  LIBRAW_Canon_RecordMode_CR2(6),
  LIBRAW_Canon_RecordMode_CR2_JPEG(7),
  LIBRAW_Canon_RecordMode_UNKNOWN(8),
  LIBRAW_Canon_RecordMode_MOV(9),
  LIBRAW_Canon_RecordMode_MP4(10),
  LIBRAW_Canon_RecordMode_CRM(11),
  LIBRAW_Canon_RecordMode_CR3(12),
  LIBRAW_Canon_RecordMode_CR3_JPEG(13),
  LIBRAW_Canon_RecordMode_HEIF(14),
  LIBRAW_Canon_RecordMode_CR3_HEIF(15),
  LIBRAW_Canon_RecordMode_TheLastOne(16);

  final int value;
  const LibRaw_Canon_RecordModes(this.value);

  static LibRaw_Canon_RecordModes fromValue(int value) => switch (value) {
    0 => LIBRAW_Canon_RecordMode_UNDEFINED,
    1 => LIBRAW_Canon_RecordMode_JPEG,
    2 => LIBRAW_Canon_RecordMode_CRW_THM,
    3 => LIBRAW_Canon_RecordMode_AVI_THM,
    4 => LIBRAW_Canon_RecordMode_TIF,
    5 => LIBRAW_Canon_RecordMode_TIF_JPEG,
    6 => LIBRAW_Canon_RecordMode_CR2,
    7 => LIBRAW_Canon_RecordMode_CR2_JPEG,
    8 => LIBRAW_Canon_RecordMode_UNKNOWN,
    9 => LIBRAW_Canon_RecordMode_MOV,
    10 => LIBRAW_Canon_RecordMode_MP4,
    11 => LIBRAW_Canon_RecordMode_CRM,
    12 => LIBRAW_Canon_RecordMode_CR3,
    13 => LIBRAW_Canon_RecordMode_CR3_JPEG,
    14 => LIBRAW_Canon_RecordMode_HEIF,
    15 => LIBRAW_Canon_RecordMode_CR3_HEIF,
    16 => LIBRAW_Canon_RecordMode_TheLastOne,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_Canon_RecordModes: $value',
    ),
  };
}

enum LibRaw_minolta_storagemethods {
  LIBRAW_MINOLTA_UNPACKED(82),
  LIBRAW_MINOLTA_PACKED(89);

  final int value;
  const LibRaw_minolta_storagemethods(this.value);

  static LibRaw_minolta_storagemethods fromValue(int value) => switch (value) {
    82 => LIBRAW_MINOLTA_UNPACKED,
    89 => LIBRAW_MINOLTA_PACKED,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_minolta_storagemethods: $value',
    ),
  };
}

enum LibRaw_minolta_bayerpatterns {
  LIBRAW_MINOLTA_RGGB(1),
  LIBRAW_MINOLTA_G2BRG1(4);

  final int value;
  const LibRaw_minolta_bayerpatterns(this.value);

  static LibRaw_minolta_bayerpatterns fromValue(int value) => switch (value) {
    1 => LIBRAW_MINOLTA_RGGB,
    4 => LIBRAW_MINOLTA_G2BRG1,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_minolta_bayerpatterns: $value',
    ),
  };
}

enum LibRaw_sony_cameratypes {
  LIBRAW_SONY_DSC(1),
  LIBRAW_SONY_DSLR(2),
  LIBRAW_SONY_NEX(3),
  LIBRAW_SONY_SLT(4),
  LIBRAW_SONY_ILCE(5),
  LIBRAW_SONY_ILCA(6),
  LIBRAW_SONY_CameraType_UNKNOWN(65535);

  final int value;
  const LibRaw_sony_cameratypes(this.value);

  static LibRaw_sony_cameratypes fromValue(int value) => switch (value) {
    1 => LIBRAW_SONY_DSC,
    2 => LIBRAW_SONY_DSLR,
    3 => LIBRAW_SONY_NEX,
    4 => LIBRAW_SONY_SLT,
    5 => LIBRAW_SONY_ILCE,
    6 => LIBRAW_SONY_ILCA,
    65535 => LIBRAW_SONY_CameraType_UNKNOWN,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_sony_cameratypes: $value',
    ),
  };
}

enum LibRaw_Sony_0x2010_Type {
  LIBRAW_SONY_Tag2010None(0),
  LIBRAW_SONY_Tag2010a(1),
  LIBRAW_SONY_Tag2010b(2),
  LIBRAW_SONY_Tag2010c(3),
  LIBRAW_SONY_Tag2010d(4),
  LIBRAW_SONY_Tag2010e(5),
  LIBRAW_SONY_Tag2010f(6),
  LIBRAW_SONY_Tag2010g(7),
  LIBRAW_SONY_Tag2010h(8),
  LIBRAW_SONY_Tag2010i(9);

  final int value;
  const LibRaw_Sony_0x2010_Type(this.value);

  static LibRaw_Sony_0x2010_Type fromValue(int value) => switch (value) {
    0 => LIBRAW_SONY_Tag2010None,
    1 => LIBRAW_SONY_Tag2010a,
    2 => LIBRAW_SONY_Tag2010b,
    3 => LIBRAW_SONY_Tag2010c,
    4 => LIBRAW_SONY_Tag2010d,
    5 => LIBRAW_SONY_Tag2010e,
    6 => LIBRAW_SONY_Tag2010f,
    7 => LIBRAW_SONY_Tag2010g,
    8 => LIBRAW_SONY_Tag2010h,
    9 => LIBRAW_SONY_Tag2010i,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_Sony_0x2010_Type: $value',
    ),
  };
}

enum LibRaw_Sony_0x9050_Type {
  LIBRAW_SONY_Tag9050None(0),
  LIBRAW_SONY_Tag9050a(1),
  LIBRAW_SONY_Tag9050b(2),
  LIBRAW_SONY_Tag9050c(3),
  LIBRAW_SONY_Tag9050d(4);

  final int value;
  const LibRaw_Sony_0x9050_Type(this.value);

  static LibRaw_Sony_0x9050_Type fromValue(int value) => switch (value) {
    0 => LIBRAW_SONY_Tag9050None,
    1 => LIBRAW_SONY_Tag9050a,
    2 => LIBRAW_SONY_Tag9050b,
    3 => LIBRAW_SONY_Tag9050c,
    4 => LIBRAW_SONY_Tag9050d,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_Sony_0x9050_Type: $value',
    ),
  };
}

enum LibRaw_KodakSensors {
  LIBRAW_Kodak_UnknownSensor(0),
  LIBRAW_Kodak_M1(1),
  LIBRAW_Kodak_M15(2),
  LIBRAW_Kodak_M16(3),
  LIBRAW_Kodak_M17(4),
  LIBRAW_Kodak_M2(5),
  LIBRAW_Kodak_M23(6),
  LIBRAW_Kodak_M24(7),
  LIBRAW_Kodak_M3(8),
  LIBRAW_Kodak_M5(9),
  LIBRAW_Kodak_M6(10),
  LIBRAW_Kodak_C14(11),
  LIBRAW_Kodak_X14(12),
  LIBRAW_Kodak_M11(13);

  final int value;
  const LibRaw_KodakSensors(this.value);

  static LibRaw_KodakSensors fromValue(int value) => switch (value) {
    0 => LIBRAW_Kodak_UnknownSensor,
    1 => LIBRAW_Kodak_M1,
    2 => LIBRAW_Kodak_M15,
    3 => LIBRAW_Kodak_M16,
    4 => LIBRAW_Kodak_M17,
    5 => LIBRAW_Kodak_M2,
    6 => LIBRAW_Kodak_M23,
    7 => LIBRAW_Kodak_M24,
    8 => LIBRAW_Kodak_M3,
    9 => LIBRAW_Kodak_M5,
    10 => LIBRAW_Kodak_M6,
    11 => LIBRAW_Kodak_C14,
    12 => LIBRAW_Kodak_X14,
    13 => LIBRAW_Kodak_M11,
    _ => throw ArgumentError('Unknown value for LibRaw_KodakSensors: $value'),
  };
}

enum LibRaw_HasselbladFormatCodes {
  LIBRAW_HF_Unknown(0),
  LIBRAW_HF_3FR(1),
  LIBRAW_HF_FFF(2),
  LIBRAW_HF_Imacon(3),
  LIBRAW_HF_HasselbladDNG(4),
  LIBRAW_HF_AdobeDNG(5),
  LIBRAW_HF_AdobeDNG_fromPhocusDNG(6);

  final int value;
  const LibRaw_HasselbladFormatCodes(this.value);

  static LibRaw_HasselbladFormatCodes fromValue(int value) => switch (value) {
    0 => LIBRAW_HF_Unknown,
    1 => LIBRAW_HF_3FR,
    2 => LIBRAW_HF_FFF,
    3 => LIBRAW_HF_Imacon,
    4 => LIBRAW_HF_HasselbladDNG,
    5 => LIBRAW_HF_AdobeDNG,
    6 => LIBRAW_HF_AdobeDNG_fromPhocusDNG,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_HasselbladFormatCodes: $value',
    ),
  };
}

enum LibRaw_rawspecial_t {
  LIBRAW_RAWSPECIAL_SONYARW2_NONE(0),
  LIBRAW_RAWSPECIAL_SONYARW2_BASEONLY(1),
  LIBRAW_RAWSPECIAL_SONYARW2_DELTAONLY(2),
  LIBRAW_RAWSPECIAL_SONYARW2_DELTAZEROBASE(4),
  LIBRAW_RAWSPECIAL_SONYARW2_DELTATOVALUE(8),
  LIBRAW_RAWSPECIAL_SONYARW2_ALLFLAGS(15),
  LIBRAW_RAWSPECIAL_NODP2Q_INTERPOLATERG(16),
  LIBRAW_RAWSPECIAL_NODP2Q_INTERPOLATEAF(32),
  LIBRAW_RAWSPECIAL_SRAW_NO_RGB(64),
  LIBRAW_RAWSPECIAL_SRAW_NO_INTERPOLATE(128);

  final int value;
  const LibRaw_rawspecial_t(this.value);

  static LibRaw_rawspecial_t fromValue(int value) => switch (value) {
    0 => LIBRAW_RAWSPECIAL_SONYARW2_NONE,
    1 => LIBRAW_RAWSPECIAL_SONYARW2_BASEONLY,
    2 => LIBRAW_RAWSPECIAL_SONYARW2_DELTAONLY,
    4 => LIBRAW_RAWSPECIAL_SONYARW2_DELTAZEROBASE,
    8 => LIBRAW_RAWSPECIAL_SONYARW2_DELTATOVALUE,
    15 => LIBRAW_RAWSPECIAL_SONYARW2_ALLFLAGS,
    16 => LIBRAW_RAWSPECIAL_NODP2Q_INTERPOLATERG,
    32 => LIBRAW_RAWSPECIAL_NODP2Q_INTERPOLATEAF,
    64 => LIBRAW_RAWSPECIAL_SRAW_NO_RGB,
    128 => LIBRAW_RAWSPECIAL_SRAW_NO_INTERPOLATE,
    _ => throw ArgumentError('Unknown value for LibRaw_rawspecial_t: $value'),
  };
}

enum LibRaw_rawspeed_bits_t {
  LIBRAW_RAWSPEEDV1_USE(1),
  LIBRAW_RAWSPEEDV1_FAILONUNKNOWN(2),
  LIBRAW_RAWSPEEDV1_IGNOREERRORS(4),
  LIBRAW_RAWSPEEDV3_USE(256),
  LIBRAW_RAWSPEEDV3_FAILONUNKNOWN(512),
  LIBRAW_RAWSPEEDV3_IGNOREERRORS(1024);

  final int value;
  const LibRaw_rawspeed_bits_t(this.value);

  static LibRaw_rawspeed_bits_t fromValue(int value) => switch (value) {
    1 => LIBRAW_RAWSPEEDV1_USE,
    2 => LIBRAW_RAWSPEEDV1_FAILONUNKNOWN,
    4 => LIBRAW_RAWSPEEDV1_IGNOREERRORS,
    256 => LIBRAW_RAWSPEEDV3_USE,
    512 => LIBRAW_RAWSPEEDV3_FAILONUNKNOWN,
    1024 => LIBRAW_RAWSPEEDV3_IGNOREERRORS,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_rawspeed_bits_t: $value',
    ),
  };
}

enum LibRaw_processing_options {
  LIBRAW_RAWOPTIONS_PENTAX_PS_ALLFRAMES(1),
  LIBRAW_RAWOPTIONS_CONVERTFLOAT_TO_INT(2),
  LIBRAW_RAWOPTIONS_ARQ_SKIP_CHANNEL_SWAP(4),
  LIBRAW_RAWOPTIONS_NO_ROTATE_FOR_KODAK_THUMBNAILS(8),
  LIBRAW_RAWOPTIONS_USE_PPM16_THUMBS(32),
  LIBRAW_RAWOPTIONS_DONT_CHECK_DNG_ILLUMINANT(64),
  LIBRAW_RAWOPTIONS_DNGSDK_ZEROCOPY(128),
  LIBRAW_RAWOPTIONS_ZEROFILTERS_FOR_MONOCHROMETIFFS(256),
  LIBRAW_RAWOPTIONS_DNG_ADD_ENHANCED(512),
  LIBRAW_RAWOPTIONS_DNG_ADD_PREVIEWS(1024),
  LIBRAW_RAWOPTIONS_DNG_PREFER_LARGEST_IMAGE(2048),
  LIBRAW_RAWOPTIONS_DNG_STAGE2(4096),
  LIBRAW_RAWOPTIONS_DNG_STAGE3(8192),
  LIBRAW_RAWOPTIONS_DNG_ALLOWSIZECHANGE(16384),
  LIBRAW_RAWOPTIONS_DNG_DISABLEWBADJUST(32768),
  LIBRAW_RAWOPTIONS_PROVIDE_NONSTANDARD_WB(65536),
  LIBRAW_RAWOPTIONS_CAMERAWB_FALLBACK_TO_DAYLIGHT(131072),
  LIBRAW_RAWOPTIONS_CHECK_THUMBNAILS_KNOWN_VENDORS(262144),
  LIBRAW_RAWOPTIONS_CHECK_THUMBNAILS_ALL_VENDORS(524288),
  LIBRAW_RAWOPTIONS_DNG_STAGE2_IFPRESENT(1048576),
  LIBRAW_RAWOPTIONS_DNG_STAGE3_IFPRESENT(2097152),
  LIBRAW_RAWOPTIONS_DNG_ADD_MASKS(4194304),
  LIBRAW_RAWOPTIONS_CANON_IGNORE_MAKERNOTES_ROTATION(8388608),
  LIBRAW_RAWOPTIONS_ALLOW_JPEGXL_PREVIEWS(16777216),
  LIBRAW_RAWOPTIONS_CANON_CHECK_CAMERA_AUTO_ROTATION_MODE(67108864),
  LIBRAW_RAWOPTIONS_DNG_STAGE23_IFPRESENT_JPGJXL(134217728);

  final int value;
  const LibRaw_processing_options(this.value);

  static LibRaw_processing_options fromValue(int value) => switch (value) {
    1 => LIBRAW_RAWOPTIONS_PENTAX_PS_ALLFRAMES,
    2 => LIBRAW_RAWOPTIONS_CONVERTFLOAT_TO_INT,
    4 => LIBRAW_RAWOPTIONS_ARQ_SKIP_CHANNEL_SWAP,
    8 => LIBRAW_RAWOPTIONS_NO_ROTATE_FOR_KODAK_THUMBNAILS,
    32 => LIBRAW_RAWOPTIONS_USE_PPM16_THUMBS,
    64 => LIBRAW_RAWOPTIONS_DONT_CHECK_DNG_ILLUMINANT,
    128 => LIBRAW_RAWOPTIONS_DNGSDK_ZEROCOPY,
    256 => LIBRAW_RAWOPTIONS_ZEROFILTERS_FOR_MONOCHROMETIFFS,
    512 => LIBRAW_RAWOPTIONS_DNG_ADD_ENHANCED,
    1024 => LIBRAW_RAWOPTIONS_DNG_ADD_PREVIEWS,
    2048 => LIBRAW_RAWOPTIONS_DNG_PREFER_LARGEST_IMAGE,
    4096 => LIBRAW_RAWOPTIONS_DNG_STAGE2,
    8192 => LIBRAW_RAWOPTIONS_DNG_STAGE3,
    16384 => LIBRAW_RAWOPTIONS_DNG_ALLOWSIZECHANGE,
    32768 => LIBRAW_RAWOPTIONS_DNG_DISABLEWBADJUST,
    65536 => LIBRAW_RAWOPTIONS_PROVIDE_NONSTANDARD_WB,
    131072 => LIBRAW_RAWOPTIONS_CAMERAWB_FALLBACK_TO_DAYLIGHT,
    262144 => LIBRAW_RAWOPTIONS_CHECK_THUMBNAILS_KNOWN_VENDORS,
    524288 => LIBRAW_RAWOPTIONS_CHECK_THUMBNAILS_ALL_VENDORS,
    1048576 => LIBRAW_RAWOPTIONS_DNG_STAGE2_IFPRESENT,
    2097152 => LIBRAW_RAWOPTIONS_DNG_STAGE3_IFPRESENT,
    4194304 => LIBRAW_RAWOPTIONS_DNG_ADD_MASKS,
    8388608 => LIBRAW_RAWOPTIONS_CANON_IGNORE_MAKERNOTES_ROTATION,
    16777216 => LIBRAW_RAWOPTIONS_ALLOW_JPEGXL_PREVIEWS,
    67108864 => LIBRAW_RAWOPTIONS_CANON_CHECK_CAMERA_AUTO_ROTATION_MODE,
    134217728 => LIBRAW_RAWOPTIONS_DNG_STAGE23_IFPRESENT_JPGJXL,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_processing_options: $value',
    ),
  };
}

enum LibRaw_decoder_flags {
  LIBRAW_DECODER_HASCURVE(16),
  LIBRAW_DECODER_SONYARW2(32),
  LIBRAW_DECODER_TRYRAWSPEED(64),
  LIBRAW_DECODER_OWNALLOC(128),
  LIBRAW_DECODER_FIXEDMAXC(256),
  LIBRAW_DECODER_ADOBECOPYPIXEL(512),
  LIBRAW_DECODER_LEGACY_WITH_MARGINS(1024),
  LIBRAW_DECODER_3CHANNEL(2048),
  LIBRAW_DECODER_FLATDATA(4096),
  LIBRAW_DECODER_FLAT_BG2_SWAPPED(8192),
  LIBRAW_DECODER_UNSUPPORTED_FORMAT(16384),
  LIBRAW_DECODER_NOTSET(32768),
  LIBRAW_DECODER_TRYRAWSPEED3(65536);

  static const LIBRAW_DECODER_SINAR4SHOT = LIBRAW_DECODER_3CHANNEL;

  final int value;
  const LibRaw_decoder_flags(this.value);

  static LibRaw_decoder_flags fromValue(int value) => switch (value) {
    16 => LIBRAW_DECODER_HASCURVE,
    32 => LIBRAW_DECODER_SONYARW2,
    64 => LIBRAW_DECODER_TRYRAWSPEED,
    128 => LIBRAW_DECODER_OWNALLOC,
    256 => LIBRAW_DECODER_FIXEDMAXC,
    512 => LIBRAW_DECODER_ADOBECOPYPIXEL,
    1024 => LIBRAW_DECODER_LEGACY_WITH_MARGINS,
    2048 => LIBRAW_DECODER_3CHANNEL,
    4096 => LIBRAW_DECODER_FLATDATA,
    8192 => LIBRAW_DECODER_FLAT_BG2_SWAPPED,
    16384 => LIBRAW_DECODER_UNSUPPORTED_FORMAT,
    32768 => LIBRAW_DECODER_NOTSET,
    65536 => LIBRAW_DECODER_TRYRAWSPEED3,
    _ => throw ArgumentError('Unknown value for LibRaw_decoder_flags: $value'),
  };

  @override
  String toString() {
    if (this == LIBRAW_DECODER_3CHANNEL)
      return "LibRaw_decoder_flags.LIBRAW_DECODER_3CHANNEL, LibRaw_decoder_flags.LIBRAW_DECODER_SINAR4SHOT";
    return super.toString();
  }
}

enum LibRaw_constructor_flags {
  LIBRAW_OPTIONS_NONE(0),
  LIBRAW_OPTIONS_NO_DATAERR_CALLBACK(2);

  static const LIBRAW_OPIONS_NO_DATAERR_CALLBACK =
      LIBRAW_OPTIONS_NO_DATAERR_CALLBACK;

  final int value;
  const LibRaw_constructor_flags(this.value);

  static LibRaw_constructor_flags fromValue(int value) => switch (value) {
    0 => LIBRAW_OPTIONS_NONE,
    2 => LIBRAW_OPTIONS_NO_DATAERR_CALLBACK,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_constructor_flags: $value',
    ),
  };

  @override
  String toString() {
    if (this == LIBRAW_OPTIONS_NO_DATAERR_CALLBACK)
      return "LibRaw_constructor_flags.LIBRAW_OPTIONS_NO_DATAERR_CALLBACK, LibRaw_constructor_flags.LIBRAW_OPIONS_NO_DATAERR_CALLBACK";
    return super.toString();
  }
}

enum LibRaw_warnings {
  LIBRAW_WARN_NONE(0),
  LIBRAW_WARN_BAD_CAMERA_WB(4),
  LIBRAW_WARN_NO_METADATA(8),
  LIBRAW_WARN_NO_JPEGLIB(16),
  LIBRAW_WARN_NO_EMBEDDED_PROFILE(32),
  LIBRAW_WARN_NO_INPUT_PROFILE(64),
  LIBRAW_WARN_BAD_OUTPUT_PROFILE(128),
  LIBRAW_WARN_NO_BADPIXELMAP(256),
  LIBRAW_WARN_BAD_DARKFRAME_FILE(512),
  LIBRAW_WARN_BAD_DARKFRAME_DIM(1024),
  LIBRAW_WARN_RAWSPEED_PROBLEM(4096),
  LIBRAW_WARN_RAWSPEED_UNSUPPORTED(8192),
  LIBRAW_WARN_RAWSPEED_PROCESSED(16384),
  LIBRAW_WARN_FALLBACK_TO_AHD(32768),
  LIBRAW_WARN_PARSEFUJI_PROCESSED(65536),
  LIBRAW_WARN_DNGSDK_PROCESSED(131072),
  LIBRAW_WARN_DNG_IMAGES_REORDERED(262144),
  LIBRAW_WARN_DNG_STAGE2_APPLIED(524288),
  LIBRAW_WARN_DNG_STAGE3_APPLIED(1048576),
  LIBRAW_WARN_RAWSPEED3_PROBLEM(2097152),
  LIBRAW_WARN_RAWSPEED3_UNSUPPORTED(4194304),
  LIBRAW_WARN_RAWSPEED3_PROCESSED(8388608),
  LIBRAW_WARN_RAWSPEED3_NOTLISTED(16777216),
  LIBRAW_WARN_VENDOR_CROP_SUGGESTED(33554432),
  LIBRAW_WARN_DNG_NOT_PROCESSED(67108864),
  LIBRAW_WARN_DNG_NOT_PARSED(134217728);

  final int value;
  const LibRaw_warnings(this.value);

  static LibRaw_warnings fromValue(int value) => switch (value) {
    0 => LIBRAW_WARN_NONE,
    4 => LIBRAW_WARN_BAD_CAMERA_WB,
    8 => LIBRAW_WARN_NO_METADATA,
    16 => LIBRAW_WARN_NO_JPEGLIB,
    32 => LIBRAW_WARN_NO_EMBEDDED_PROFILE,
    64 => LIBRAW_WARN_NO_INPUT_PROFILE,
    128 => LIBRAW_WARN_BAD_OUTPUT_PROFILE,
    256 => LIBRAW_WARN_NO_BADPIXELMAP,
    512 => LIBRAW_WARN_BAD_DARKFRAME_FILE,
    1024 => LIBRAW_WARN_BAD_DARKFRAME_DIM,
    4096 => LIBRAW_WARN_RAWSPEED_PROBLEM,
    8192 => LIBRAW_WARN_RAWSPEED_UNSUPPORTED,
    16384 => LIBRAW_WARN_RAWSPEED_PROCESSED,
    32768 => LIBRAW_WARN_FALLBACK_TO_AHD,
    65536 => LIBRAW_WARN_PARSEFUJI_PROCESSED,
    131072 => LIBRAW_WARN_DNGSDK_PROCESSED,
    262144 => LIBRAW_WARN_DNG_IMAGES_REORDERED,
    524288 => LIBRAW_WARN_DNG_STAGE2_APPLIED,
    1048576 => LIBRAW_WARN_DNG_STAGE3_APPLIED,
    2097152 => LIBRAW_WARN_RAWSPEED3_PROBLEM,
    4194304 => LIBRAW_WARN_RAWSPEED3_UNSUPPORTED,
    8388608 => LIBRAW_WARN_RAWSPEED3_PROCESSED,
    16777216 => LIBRAW_WARN_RAWSPEED3_NOTLISTED,
    33554432 => LIBRAW_WARN_VENDOR_CROP_SUGGESTED,
    67108864 => LIBRAW_WARN_DNG_NOT_PROCESSED,
    134217728 => LIBRAW_WARN_DNG_NOT_PARSED,
    _ => throw ArgumentError('Unknown value for LibRaw_warnings: $value'),
  };
}

enum LibRaw_exceptions {
  LIBRAW_EXCEPTION_NONE(0),
  LIBRAW_EXCEPTION_ALLOC(1),
  LIBRAW_EXCEPTION_DECODE_RAW(2),
  LIBRAW_EXCEPTION_DECODE_JPEG(3),
  LIBRAW_EXCEPTION_IO_EOF(4),
  LIBRAW_EXCEPTION_IO_CORRUPT(5),
  LIBRAW_EXCEPTION_CANCELLED_BY_CALLBACK(6),
  LIBRAW_EXCEPTION_BAD_CROP(7),
  LIBRAW_EXCEPTION_IO_BADFILE(8),
  LIBRAW_EXCEPTION_DECODE_JPEG2000(9),
  LIBRAW_EXCEPTION_TOOBIG(10),
  LIBRAW_EXCEPTION_MEMPOOL(11),
  LIBRAW_EXCEPTION_UNSUPPORTED_FORMAT(12);

  final int value;
  const LibRaw_exceptions(this.value);

  static LibRaw_exceptions fromValue(int value) => switch (value) {
    0 => LIBRAW_EXCEPTION_NONE,
    1 => LIBRAW_EXCEPTION_ALLOC,
    2 => LIBRAW_EXCEPTION_DECODE_RAW,
    3 => LIBRAW_EXCEPTION_DECODE_JPEG,
    4 => LIBRAW_EXCEPTION_IO_EOF,
    5 => LIBRAW_EXCEPTION_IO_CORRUPT,
    6 => LIBRAW_EXCEPTION_CANCELLED_BY_CALLBACK,
    7 => LIBRAW_EXCEPTION_BAD_CROP,
    8 => LIBRAW_EXCEPTION_IO_BADFILE,
    9 => LIBRAW_EXCEPTION_DECODE_JPEG2000,
    10 => LIBRAW_EXCEPTION_TOOBIG,
    11 => LIBRAW_EXCEPTION_MEMPOOL,
    12 => LIBRAW_EXCEPTION_UNSUPPORTED_FORMAT,
    _ => throw ArgumentError('Unknown value for LibRaw_exceptions: $value'),
  };
}

enum LibRaw_progress {
  LIBRAW_PROGRESS_START(0),
  LIBRAW_PROGRESS_OPEN(1),
  LIBRAW_PROGRESS_IDENTIFY(2),
  LIBRAW_PROGRESS_SIZE_ADJUST(4),
  LIBRAW_PROGRESS_LOAD_RAW(8),
  LIBRAW_PROGRESS_RAW2_IMAGE(16),
  LIBRAW_PROGRESS_REMOVE_ZEROES(32),
  LIBRAW_PROGRESS_BAD_PIXELS(64),
  LIBRAW_PROGRESS_DARK_FRAME(128),
  LIBRAW_PROGRESS_FOVEON_INTERPOLATE(256),
  LIBRAW_PROGRESS_SCALE_COLORS(512),
  LIBRAW_PROGRESS_PRE_INTERPOLATE(1024),
  LIBRAW_PROGRESS_INTERPOLATE(2048),
  LIBRAW_PROGRESS_MIX_GREEN(4096),
  LIBRAW_PROGRESS_MEDIAN_FILTER(8192),
  LIBRAW_PROGRESS_HIGHLIGHTS(16384),
  LIBRAW_PROGRESS_FUJI_ROTATE(32768),
  LIBRAW_PROGRESS_FLIP(65536),
  LIBRAW_PROGRESS_APPLY_PROFILE(131072),
  LIBRAW_PROGRESS_CONVERT_RGB(262144),
  LIBRAW_PROGRESS_STRETCH(524288),
  LIBRAW_PROGRESS_STAGE20(1048576),
  LIBRAW_PROGRESS_STAGE21(2097152),
  LIBRAW_PROGRESS_STAGE22(4194304),
  LIBRAW_PROGRESS_STAGE23(8388608),
  LIBRAW_PROGRESS_STAGE24(16777216),
  LIBRAW_PROGRESS_STAGE25(33554432),
  LIBRAW_PROGRESS_STAGE26(67108864),
  LIBRAW_PROGRESS_STAGE27(134217728),
  LIBRAW_PROGRESS_THUMB_LOAD(268435456),
  LIBRAW_PROGRESS_TRESERVED1(536870912),
  LIBRAW_PROGRESS_TRESERVED2(1073741824);

  final int value;
  const LibRaw_progress(this.value);

  static LibRaw_progress fromValue(int value) => switch (value) {
    0 => LIBRAW_PROGRESS_START,
    1 => LIBRAW_PROGRESS_OPEN,
    2 => LIBRAW_PROGRESS_IDENTIFY,
    4 => LIBRAW_PROGRESS_SIZE_ADJUST,
    8 => LIBRAW_PROGRESS_LOAD_RAW,
    16 => LIBRAW_PROGRESS_RAW2_IMAGE,
    32 => LIBRAW_PROGRESS_REMOVE_ZEROES,
    64 => LIBRAW_PROGRESS_BAD_PIXELS,
    128 => LIBRAW_PROGRESS_DARK_FRAME,
    256 => LIBRAW_PROGRESS_FOVEON_INTERPOLATE,
    512 => LIBRAW_PROGRESS_SCALE_COLORS,
    1024 => LIBRAW_PROGRESS_PRE_INTERPOLATE,
    2048 => LIBRAW_PROGRESS_INTERPOLATE,
    4096 => LIBRAW_PROGRESS_MIX_GREEN,
    8192 => LIBRAW_PROGRESS_MEDIAN_FILTER,
    16384 => LIBRAW_PROGRESS_HIGHLIGHTS,
    32768 => LIBRAW_PROGRESS_FUJI_ROTATE,
    65536 => LIBRAW_PROGRESS_FLIP,
    131072 => LIBRAW_PROGRESS_APPLY_PROFILE,
    262144 => LIBRAW_PROGRESS_CONVERT_RGB,
    524288 => LIBRAW_PROGRESS_STRETCH,
    1048576 => LIBRAW_PROGRESS_STAGE20,
    2097152 => LIBRAW_PROGRESS_STAGE21,
    4194304 => LIBRAW_PROGRESS_STAGE22,
    8388608 => LIBRAW_PROGRESS_STAGE23,
    16777216 => LIBRAW_PROGRESS_STAGE24,
    33554432 => LIBRAW_PROGRESS_STAGE25,
    67108864 => LIBRAW_PROGRESS_STAGE26,
    134217728 => LIBRAW_PROGRESS_STAGE27,
    268435456 => LIBRAW_PROGRESS_THUMB_LOAD,
    536870912 => LIBRAW_PROGRESS_TRESERVED1,
    1073741824 => LIBRAW_PROGRESS_TRESERVED2,
    _ => throw ArgumentError('Unknown value for LibRaw_progress: $value'),
  };
}

enum LibRaw_errors {
  LIBRAW_SUCCESS(0),
  LIBRAW_UNSPECIFIED_ERROR(-1),
  LIBRAW_FILE_UNSUPPORTED(-2),
  LIBRAW_REQUEST_FOR_NONEXISTENT_IMAGE(-3),
  LIBRAW_OUT_OF_ORDER_CALL(-4),
  LIBRAW_NO_THUMBNAIL(-5),
  LIBRAW_UNSUPPORTED_THUMBNAIL(-6),
  LIBRAW_INPUT_CLOSED(-7),
  LIBRAW_NOT_IMPLEMENTED(-8),
  LIBRAW_REQUEST_FOR_NONEXISTENT_THUMBNAIL(-9),
  LIBRAW_UNSUFFICIENT_MEMORY(-100007),
  LIBRAW_DATA_ERROR(-100008),
  LIBRAW_IO_ERROR(-100009),
  LIBRAW_CANCELLED_BY_CALLBACK(-100010),
  LIBRAW_BAD_CROP(-100011),
  LIBRAW_TOO_BIG(-100012),
  LIBRAW_MEMPOOL_OVERFLOW(-100013);

  final int value;
  const LibRaw_errors(this.value);

  static LibRaw_errors fromValue(int value) => switch (value) {
    0 => LIBRAW_SUCCESS,
    -1 => LIBRAW_UNSPECIFIED_ERROR,
    -2 => LIBRAW_FILE_UNSUPPORTED,
    -3 => LIBRAW_REQUEST_FOR_NONEXISTENT_IMAGE,
    -4 => LIBRAW_OUT_OF_ORDER_CALL,
    -5 => LIBRAW_NO_THUMBNAIL,
    -6 => LIBRAW_UNSUPPORTED_THUMBNAIL,
    -7 => LIBRAW_INPUT_CLOSED,
    -8 => LIBRAW_NOT_IMPLEMENTED,
    -9 => LIBRAW_REQUEST_FOR_NONEXISTENT_THUMBNAIL,
    -100007 => LIBRAW_UNSUFFICIENT_MEMORY,
    -100008 => LIBRAW_DATA_ERROR,
    -100009 => LIBRAW_IO_ERROR,
    -100010 => LIBRAW_CANCELLED_BY_CALLBACK,
    -100011 => LIBRAW_BAD_CROP,
    -100012 => LIBRAW_TOO_BIG,
    -100013 => LIBRAW_MEMPOOL_OVERFLOW,
    _ => throw ArgumentError('Unknown value for LibRaw_errors: $value'),
  };
}

enum LibRaw_internal_thumbnail_formats {
  LIBRAW_INTERNAL_THUMBNAIL_UNKNOWN(0),
  LIBRAW_INTERNAL_THUMBNAIL_KODAK_THUMB(1),
  LIBRAW_INTERNAL_THUMBNAIL_KODAK_YCBCR(2),
  LIBRAW_INTERNAL_THUMBNAIL_KODAK_RGB(3),
  LIBRAW_INTERNAL_THUMBNAIL_JPEG(4),
  LIBRAW_INTERNAL_THUMBNAIL_LAYER(5),
  LIBRAW_INTERNAL_THUMBNAIL_ROLLEI(6),
  LIBRAW_INTERNAL_THUMBNAIL_PPM(7),
  LIBRAW_INTERNAL_THUMBNAIL_PPM16(8),
  LIBRAW_INTERNAL_THUMBNAIL_X3F(9),
  LIBRAW_INTERNAL_THUMBNAIL_DNG_YCBCR(10),
  LIBRAW_INTERNAL_THUMBNAIL_JPEGXL(11);

  final int value;
  const LibRaw_internal_thumbnail_formats(this.value);

  static LibRaw_internal_thumbnail_formats fromValue(int value) =>
      switch (value) {
        0 => LIBRAW_INTERNAL_THUMBNAIL_UNKNOWN,
        1 => LIBRAW_INTERNAL_THUMBNAIL_KODAK_THUMB,
        2 => LIBRAW_INTERNAL_THUMBNAIL_KODAK_YCBCR,
        3 => LIBRAW_INTERNAL_THUMBNAIL_KODAK_RGB,
        4 => LIBRAW_INTERNAL_THUMBNAIL_JPEG,
        5 => LIBRAW_INTERNAL_THUMBNAIL_LAYER,
        6 => LIBRAW_INTERNAL_THUMBNAIL_ROLLEI,
        7 => LIBRAW_INTERNAL_THUMBNAIL_PPM,
        8 => LIBRAW_INTERNAL_THUMBNAIL_PPM16,
        9 => LIBRAW_INTERNAL_THUMBNAIL_X3F,
        10 => LIBRAW_INTERNAL_THUMBNAIL_DNG_YCBCR,
        11 => LIBRAW_INTERNAL_THUMBNAIL_JPEGXL,
        _ => throw ArgumentError(
          'Unknown value for LibRaw_internal_thumbnail_formats: $value',
        ),
      };
}

enum LibRaw_thumbnail_formats {
  LIBRAW_THUMBNAIL_UNKNOWN(0),
  LIBRAW_THUMBNAIL_JPEG(1),
  LIBRAW_THUMBNAIL_BITMAP(2),
  LIBRAW_THUMBNAIL_BITMAP16(3),
  LIBRAW_THUMBNAIL_LAYER(4),
  LIBRAW_THUMBNAIL_ROLLEI(5),
  LIBRAW_THUMBNAIL_H265(6),
  LIBRAW_THUMBNAIL_JPEGXL(7);

  final int value;
  const LibRaw_thumbnail_formats(this.value);

  static LibRaw_thumbnail_formats fromValue(int value) => switch (value) {
    0 => LIBRAW_THUMBNAIL_UNKNOWN,
    1 => LIBRAW_THUMBNAIL_JPEG,
    2 => LIBRAW_THUMBNAIL_BITMAP,
    3 => LIBRAW_THUMBNAIL_BITMAP16,
    4 => LIBRAW_THUMBNAIL_LAYER,
    5 => LIBRAW_THUMBNAIL_ROLLEI,
    6 => LIBRAW_THUMBNAIL_H265,
    7 => LIBRAW_THUMBNAIL_JPEGXL,
    _ => throw ArgumentError(
      'Unknown value for LibRaw_thumbnail_formats: $value',
    ),
  };
}

enum LibRaw_image_formats {
  LIBRAW_IMAGE_JPEG(1),
  LIBRAW_IMAGE_BITMAP(2),
  LIBRAW_IMAGE_JPEGXL(3),
  LIBRAW_IMAGE_H265(4);

  final int value;
  const LibRaw_image_formats(this.value);

  static LibRaw_image_formats fromValue(int value) => switch (value) {
    1 => LIBRAW_IMAGE_JPEG,
    2 => LIBRAW_IMAGE_BITMAP,
    3 => LIBRAW_IMAGE_JPEGXL,
    4 => LIBRAW_IMAGE_H265,
    _ => throw ArgumentError('Unknown value for LibRaw_image_formats: $value'),
  };
}

typedef INT64 = ffi.LongLong;
typedef DartINT64 = int;
typedef UINT64 = ffi.UnsignedLongLong;
typedef DartUINT64 = int;
typedef uchar = ffi.UnsignedChar;
typedef Dartuchar = int;
typedef ushort = ffi.UnsignedShort;
typedef Dartushort = int;

final class libraw_decoder_info_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> decoder_name;

  @ffi.UnsignedInt()
  external int decoder_flags;
}

final class libraw_internal_output_params_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int mix_green;

  @ffi.UnsignedInt()
  external int raw_color;

  @ffi.UnsignedInt()
  external int zero_is_bad;

  @ushort()
  external int shrink;

  @ushort()
  external int fuji_width;
}

typedef memory_callbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> data,
      ffi.Pointer<ffi.Char> file,
      ffi.Pointer<ffi.Char> where,
    );
typedef Dartmemory_callbackFunction =
    void Function(
      ffi.Pointer<ffi.Void> data,
      ffi.Pointer<ffi.Char> file,
      ffi.Pointer<ffi.Char> where,
    );
typedef memory_callback =
    ffi.Pointer<ffi.NativeFunction<memory_callbackFunction>>;
typedef exif_parser_callbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> context,
      ffi.Int tag,
      ffi.Int type,
      ffi.Int len,
      ffi.UnsignedInt ord,
      ffi.Pointer<ffi.Void> ifp,
      INT64 base,
    );
typedef Dartexif_parser_callbackFunction =
    void Function(
      ffi.Pointer<ffi.Void> context,
      int tag,
      int type,
      int len,
      int ord,
      ffi.Pointer<ffi.Void> ifp,
      DartINT64 base,
    );
typedef exif_parser_callback =
    ffi.Pointer<ffi.NativeFunction<exif_parser_callbackFunction>>;
typedef data_callbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> data,
      ffi.Pointer<ffi.Char> file,
      INT64 offset,
    );
typedef Dartdata_callbackFunction =
    void Function(
      ffi.Pointer<ffi.Void> data,
      ffi.Pointer<ffi.Char> file,
      DartINT64 offset,
    );
typedef data_callback = ffi.Pointer<ffi.NativeFunction<data_callbackFunction>>;
typedef progress_callbackFunction =
    ffi.Int Function(
      ffi.Pointer<ffi.Void> data,
      ffi.UnsignedInt stage,
      ffi.Int iteration,
      ffi.Int expected,
    );
typedef Dartprogress_callbackFunction =
    int Function(
      ffi.Pointer<ffi.Void> data,
      LibRaw_progress stage,
      int iteration,
      int expected,
    );
typedef progress_callback =
    ffi.Pointer<ffi.NativeFunction<progress_callbackFunction>>;
typedef pre_identify_callbackFunction =
    ffi.Int Function(ffi.Pointer<ffi.Void> ctx);
typedef Dartpre_identify_callbackFunction =
    int Function(ffi.Pointer<ffi.Void> ctx);
typedef pre_identify_callback =
    ffi.Pointer<ffi.NativeFunction<pre_identify_callbackFunction>>;
typedef post_identify_callbackFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> ctx);
typedef Dartpost_identify_callbackFunction =
    void Function(ffi.Pointer<ffi.Void> ctx);
typedef post_identify_callback =
    ffi.Pointer<ffi.NativeFunction<post_identify_callbackFunction>>;
typedef process_step_callbackFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> ctx);
typedef Dartprocess_step_callbackFunction =
    void Function(ffi.Pointer<ffi.Void> ctx);
typedef process_step_callback =
    ffi.Pointer<ffi.NativeFunction<process_step_callbackFunction>>;

final class libraw_callbacks_t extends ffi.Struct {
  external data_callback data_cb;

  external ffi.Pointer<ffi.Void> datacb_data;

  external progress_callback progress_cb;

  external ffi.Pointer<ffi.Void> progresscb_data;

  external exif_parser_callback exif_cb;

  external exif_parser_callback makernotes_cb;

  external ffi.Pointer<ffi.Void> exifparser_data;

  external ffi.Pointer<ffi.Void> makernotesparser_data;

  external pre_identify_callback pre_identify_cb;

  external post_identify_callback post_identify_cb;

  external process_step_callback pre_subtractblack_cb;

  external process_step_callback pre_scalecolors_cb;

  external process_step_callback pre_preinterpolate_cb;

  external process_step_callback pre_interpolate_cb;

  external process_step_callback interpolate_bayer_cb;

  external process_step_callback interpolate_xtrans_cb;

  external process_step_callback post_interpolate_cb;

  external process_step_callback pre_converttorgb_cb;

  external process_step_callback post_converttorgb_cb;
}

final class libraw_processed_image_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  LibRaw_image_formats get type => LibRaw_image_formats.fromValue(typeAsInt);

  @ushort()
  external int height;

  @ushort()
  external int width;

  @ushort()
  external int colors;

  @ushort()
  external int bits;

  @ffi.UnsignedInt()
  external int data_size;

  @ffi.Array.multi([1])
  external ffi.Array<ffi.UnsignedChar> data;
}

final class libraw_iparams_t extends ffi.Struct {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> guard;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> make;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> model;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> software;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> normalized_make;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> normalized_model;

  @ffi.UnsignedInt()
  external int maker_index;

  @ffi.UnsignedInt()
  external int raw_count;

  @ffi.UnsignedInt()
  external int dng_version;

  @ffi.UnsignedInt()
  external int is_foveon;

  @ffi.Int()
  external int colors;

  @ffi.UnsignedInt()
  external int filters;

  @ffi.Array.multi([6, 6])
  external ffi.Array<ffi.Array<ffi.Char>> xtrans;

  @ffi.Array.multi([6, 6])
  external ffi.Array<ffi.Array<ffi.Char>> xtrans_abs;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.Char> cdesc;

  @ffi.UnsignedInt()
  external int xmplen;

  external ffi.Pointer<ffi.Char> xmpdata;
}

final class libraw_raw_inset_crop_t extends ffi.Struct {
  @ushort()
  external int cleft;

  @ushort()
  external int ctop;

  @ushort()
  external int cwidth;

  @ushort()
  external int cheight;
}

final class libraw_image_sizes_t extends ffi.Struct {
  @ushort()
  external int raw_height;

  @ushort()
  external int raw_width;

  @ushort()
  external int height;

  @ushort()
  external int width;

  @ushort()
  external int top_margin;

  @ushort()
  external int left_margin;

  @ushort()
  external int iheight;

  @ushort()
  external int iwidth;

  @ffi.UnsignedInt()
  external int raw_pitch;

  @ffi.Double()
  external double pixel_aspect;

  @ffi.Int()
  external int flip;

  @ffi.Array.multi([8, 4])
  external ffi.Array<ffi.Array<ffi.Int>> mask;

  @ushort()
  external int raw_aspect;

  @ffi.Array.multi([2])
  external ffi.Array<libraw_raw_inset_crop_t> raw_inset_crops;
}

final class libraw_area_t extends ffi.Struct {
  @ffi.Short()
  external int t;

  @ffi.Short()
  external int l;

  @ffi.Short()
  external int b;

  @ffi.Short()
  external int r;
}

final class ph1_t extends ffi.Struct {
  @ffi.Int()
  external int format;

  @ffi.Int()
  external int key_off;

  @ffi.Int()
  external int tag_21a;

  @ffi.Int()
  external int t_black;

  @ffi.Int()
  external int split_col;

  @ffi.Int()
  external int black_col;

  @ffi.Int()
  external int split_row;

  @ffi.Int()
  external int black_row;

  @ffi.Float()
  external double tag_210;
}

final class libraw_dng_color_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int parsedfields;

  @ushort()
  external int illuminant;

  @ffi.Array.multi([4, 4])
  external ffi.Array<ffi.Array<ffi.Float>> calibration;

  @ffi.Array.multi([4, 3])
  external ffi.Array<ffi.Array<ffi.Float>> colormatrix;

  @ffi.Array.multi([3, 4])
  external ffi.Array<ffi.Array<ffi.Float>> forwardmatrix;
}

final class libraw_dng_rawopcode_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int len;

  external ffi.Pointer<ffi.Void> data;
}

final class libraw_dng_levels_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int parsedfields;

  @ffi.Array.multi([4104])
  external ffi.Array<ffi.UnsignedInt> dng_cblack;

  @ffi.UnsignedInt()
  external int dng_black;

  @ffi.Array.multi([4104])
  external ffi.Array<ffi.Float> dng_fcblack;

  @ffi.Float()
  external double dng_fblack;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.UnsignedInt> dng_whitelevel;

  @ffi.Array.multi([4])
  external ffi.Array<ushort> default_crop;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> user_crop;

  @ffi.UnsignedInt()
  external int preview_colorspace;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> analogbalance;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> asshotneutral;

  @ffi.Float()
  external double baseline_exposure;

  @ffi.Float()
  external double LinearResponseLimit;

  @ffi.Array.multi([3])
  external ffi.Array<libraw_dng_rawopcode_t> rawopcodes;
}

final class libraw_P1_color_t extends ffi.Struct {
  @ffi.Array.multi([9])
  external ffi.Array<ffi.Float> romm_cam;
}

final class libraw_canon_makernotes_t extends ffi.Struct {
  @ffi.Int()
  external int ColorDataVer;

  @ffi.Int()
  external int ColorDataSubVer;

  @ffi.Int()
  external int SpecularWhiteLevel;

  @ffi.Int()
  external int NormalWhiteLevel;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Int> ChannelBlackLevel;

  @ffi.Int()
  external int AverageBlackLevel;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.UnsignedInt> multishot;

  @ffi.Short()
  external int MeteringMode;

  @ffi.Short()
  external int SpotMeteringMode;

  @uchar()
  external int FlashMeteringMode;

  @ffi.Short()
  external int FlashExposureLock;

  @ffi.Short()
  external int ExposureMode;

  @ffi.Short()
  external int AESetting;

  @ffi.Short()
  external int ImageStabilization;

  @ffi.Short()
  external int FlashMode;

  @ffi.Short()
  external int FlashActivity;

  @ffi.Short()
  external int FlashBits;

  @ffi.Short()
  external int ManualFlashOutput;

  @ffi.Short()
  external int FlashOutput;

  @ffi.Short()
  external int FlashGuideNumber;

  @ffi.Short()
  external int ContinuousDrive;

  @ffi.Short()
  external int SensorWidth;

  @ffi.Short()
  external int SensorHeight;

  @ffi.Int()
  external int AFMicroAdjMode;

  @ffi.Float()
  external double AFMicroAdjValue;

  @ffi.Short()
  external int MakernotesFlip;

  @ffi.Short()
  external int AutoRotateMode;

  @ffi.Short()
  external int RecordMode;

  @ffi.Short()
  external int SRAWQuality;

  @ffi.UnsignedInt()
  external int wbi;

  @ffi.Short()
  external int RF_lensID;

  @ffi.Int()
  external int AutoLightingOptimizer;

  @ffi.Int()
  external int HighlightTonePriority;

  @ffi.Short()
  external int Quality;

  @ffi.Int()
  external int CanonLog;

  external libraw_area_t DefaultCropAbsolute;

  external libraw_area_t RecommendedImageArea;

  external libraw_area_t LeftOpticalBlack;

  external libraw_area_t UpperOpticalBlack;

  external libraw_area_t ActiveArea;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Short> ISOgain;
}

final class libraw_hasselblad_makernotes_t extends ffi.Struct {
  @ffi.Int()
  external int BaseISO;

  @ffi.Double()
  external double Gain;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> Sensor;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> SensorUnit;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> HostBody;

  @ffi.Int()
  external int SensorCode;

  @ffi.Int()
  external int SensorSubCode;

  @ffi.Int()
  external int CoatingCode;

  @ffi.Int()
  external int uncropped;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> CaptureSequenceInitiator;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> SensorUnitConnector;

  @ffi.Int()
  external int format;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> nIFD_CM;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> RecommendedCrop;

  @ffi.Array.multi([4, 3])
  external ffi.Array<ffi.Array<ffi.Double>> mnColorMatrix;
}

final class libraw_fuji_info_t extends ffi.Struct {
  @ffi.Float()
  external double ExpoMidPointShift;

  @ushort()
  external int DynamicRange;

  @ushort()
  external int FilmMode;

  @ushort()
  external int DynamicRangeSetting;

  @ushort()
  external int DevelopmentDynamicRange;

  @ushort()
  external int AutoDynamicRange;

  @ushort()
  external int DRangePriority;

  @ushort()
  external int DRangePriorityAuto;

  @ushort()
  external int DRangePriorityFixed;

  @ffi.Array.multi([33])
  external ffi.Array<ffi.Char> FujiModel;

  @ffi.Array.multi([33])
  external ffi.Array<ffi.Char> FujiModel2;

  @ffi.Float()
  external double BrightnessCompensation;

  @ushort()
  external int FocusMode;

  @ushort()
  external int AFMode;

  @ffi.Array.multi([2])
  external ffi.Array<ushort> FocusPixel;

  @ushort()
  external int PrioritySettings;

  @ffi.UnsignedInt()
  external int FocusSettings;

  @ffi.UnsignedInt()
  external int AF_C_Settings;

  @ushort()
  external int FocusWarning;

  @ffi.Array.multi([3])
  external ffi.Array<ushort> ImageStabilization;

  @ushort()
  external int FlashMode;

  @ushort()
  external int WB_Preset;

  @ushort()
  external int ShutterType;

  @ushort()
  external int ExrMode;

  @ushort()
  external int Macro;

  @ffi.UnsignedInt()
  external int Rating;

  @ushort()
  external int CropMode;

  @ffi.Array.multi([13])
  external ffi.Array<ffi.Char> SerialSignature;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.Char> SensorID;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.Char> RAFVersion;

  @ffi.Int()
  external int RAFDataGeneration;

  @ushort()
  external int RAFDataVersion;

  @ffi.Int()
  external int isTSNERDTS;

  @ffi.Short()
  external int DriveMode;

  @ffi.Array.multi([9])
  external ffi.Array<ushort> BlackLevel;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.UnsignedInt> RAFData_ImageSizeTable;

  @ffi.Int()
  external int AutoBracketing;

  @ffi.Int()
  external int SequenceNumber;

  @ffi.Int()
  external int SeriesLength;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Float> PixelShiftOffset;

  @ffi.Int()
  external int ImageCount;
}

final class libraw_sensor_highspeed_crop_t extends ffi.Struct {
  @ushort()
  external int cleft;

  @ushort()
  external int ctop;

  @ushort()
  external int cwidth;

  @ushort()
  external int cheight;
}

final class libraw_nikon_makernotes_t extends ffi.Struct {
  @ffi.Double()
  external double ExposureBracketValue;

  @ushort()
  external int ActiveDLighting;

  @ushort()
  external int ShootingMode;

  @ffi.Array.multi([7])
  external ffi.Array<uchar> ImageStabilization;

  @uchar()
  external int VibrationReduction;

  @uchar()
  external int VRMode;

  @ffi.Array.multi([13])
  external ffi.Array<ffi.Char> FlashSetting;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Char> FlashType;

  @ffi.Array.multi([4])
  external ffi.Array<uchar> FlashExposureCompensation;

  @ffi.Array.multi([4])
  external ffi.Array<uchar> ExternalFlashExposureComp;

  @ffi.Array.multi([4])
  external ffi.Array<uchar> FlashExposureBracketValue;

  @uchar()
  external int FlashMode;

  @ffi.SignedChar()
  external int FlashExposureCompensation2;

  @ffi.SignedChar()
  external int FlashExposureCompensation3;

  @ffi.SignedChar()
  external int FlashExposureCompensation4;

  @uchar()
  external int FlashSource;

  @ffi.Array.multi([2])
  external ffi.Array<uchar> FlashFirmware;

  @uchar()
  external int ExternalFlashFlags;

  @uchar()
  external int FlashControlCommanderMode;

  @uchar()
  external int FlashOutputAndCompensation;

  @uchar()
  external int FlashFocalLength;

  @uchar()
  external int FlashGNDistance;

  @ffi.Array.multi([4])
  external ffi.Array<uchar> FlashGroupControlMode;

  @ffi.Array.multi([4])
  external ffi.Array<uchar> FlashGroupOutputAndCompensation;

  @uchar()
  external int FlashColorFilter;

  @ushort()
  external int NEFCompression;

  @ffi.Int()
  external int ExposureMode;

  @ffi.Int()
  external int ExposureProgram;

  @ffi.Int()
  external int nMEshots;

  @ffi.Int()
  external int MEgainOn;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Double> ME_WB;

  @uchar()
  external int AFFineTune;

  @uchar()
  external int AFFineTuneIndex;

  @ffi.Int8()
  external int AFFineTuneAdj;

  @ffi.UnsignedInt()
  external int LensDataVersion;

  @ffi.UnsignedInt()
  external int FlashInfoVersion;

  @ffi.UnsignedInt()
  external int ColorBalanceVersion;

  @uchar()
  external int key;

  @ffi.Array.multi([4])
  external ffi.Array<ushort> NEFBitDepth;

  @ushort()
  external int HighSpeedCropFormat;

  external libraw_sensor_highspeed_crop_t SensorHighSpeedCrop;

  @ushort()
  external int SensorWidth;

  @ushort()
  external int SensorHeight;

  @ushort()
  external int Active_D_Lighting;

  @ffi.UnsignedInt()
  external int PictureControlVersion;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Char> PictureControlName;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Char> PictureControlBase;

  @ffi.UnsignedInt()
  external int ShotInfoVersion;

  @ffi.Array.multi([9])
  external ffi.Array<ffi.Char> ShotInfoFirmware;

  @ffi.UnsignedInt()
  external int BurstTable_0x0056_len;

  external ffi.Pointer<uchar> BurstTable_0x0056;

  @ushort()
  external int BurstTable_0x0056_ver;

  @ushort()
  external int BurstTable_0x0056_gid;

  @uchar()
  external int BurstTable_0x0056_fnum;

  @ffi.Short()
  external int MakernotesFlip;

  @ffi.Double()
  external double RollAngle;

  @ffi.Double()
  external double PitchAngle;

  @ffi.Double()
  external double YawAngle;
}

final class libraw_olympus_makernotes_t extends ffi.Struct {
  @ffi.Array.multi([6])
  external ffi.Array<ffi.Char> CameraType2;

  @ushort()
  external int ValidBits;

  @ffi.UnsignedInt()
  external int tagX640;

  @ffi.UnsignedInt()
  external int tagX641;

  @ffi.UnsignedInt()
  external int tagX642;

  @ffi.UnsignedInt()
  external int tagX643;

  @ffi.UnsignedInt()
  external int tagX644;

  @ffi.UnsignedInt()
  external int tagX645;

  @ffi.UnsignedInt()
  external int tagX646;

  @ffi.UnsignedInt()
  external int tagX647;

  @ffi.UnsignedInt()
  external int tagX648;

  @ffi.UnsignedInt()
  external int tagX649;

  @ffi.UnsignedInt()
  external int tagX650;

  @ffi.UnsignedInt()
  external int tagX651;

  @ffi.UnsignedInt()
  external int tagX652;

  @ffi.UnsignedInt()
  external int tagX653;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> SensorCalibration;

  @ffi.Array.multi([5])
  external ffi.Array<ushort> DriveMode;

  @ushort()
  external int ColorSpace;

  @ffi.Array.multi([2])
  external ffi.Array<ushort> FocusMode;

  @ushort()
  external int AutoFocus;

  @ushort()
  external int AFPoint;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.UnsignedInt> AFAreas;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.Double> AFPointSelected;

  @ushort()
  external int AFResult;

  @uchar()
  external int AFFineTune;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Short> AFFineTuneAdj;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedInt> SpecialMode;

  @ushort()
  external int ZoomStepCount;

  @ushort()
  external int FocusStepCount;

  @ushort()
  external int FocusStepInfinity;

  @ushort()
  external int FocusStepNear;

  @ffi.Double()
  external double FocusDistance;

  @ffi.Array.multi([4])
  external ffi.Array<ushort> AspectFrame;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> StackedImage;

  @uchar()
  external int isLiveND;

  @ffi.UnsignedInt()
  external int LiveNDfactor;

  @ushort()
  external int Panorama_mode;

  @ushort()
  external int Panorama_frameNum;
}

final class libraw_panasonic_makernotes_t extends ffi.Struct {
  @ushort()
  external int Compression;

  @ushort()
  external int BlackLevelDim;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Float> BlackLevel;

  @ffi.UnsignedInt()
  external int Multishot;

  @ffi.Float()
  external double gamma;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Int> HighISOMultiplier;

  @ffi.Short()
  external int FocusStepNear;

  @ffi.Short()
  external int FocusStepCount;

  @ffi.UnsignedInt()
  external int ZoomPosition;

  @ffi.UnsignedInt()
  external int LensManufacturer;
}

final class libraw_pentax_makernotes_t extends ffi.Struct {
  @ffi.Array.multi([4])
  external ffi.Array<uchar> DriveMode;

  @ffi.Array.multi([2])
  external ffi.Array<ushort> FocusMode;

  @ffi.Array.multi([2])
  external ffi.Array<ushort> AFPointSelected;

  @ushort()
  external int AFPointSelected_Area;

  @ffi.Int()
  external int AFPointsInFocus_version;

  @ffi.UnsignedInt()
  external int AFPointsInFocus;

  @ushort()
  external int FocusPosition;

  @ffi.Array.multi([4])
  external ffi.Array<uchar> DynamicRangeExpansion;

  @ffi.Short()
  external int AFAdjustment;

  @uchar()
  external int AFPointMode;

  @uchar()
  external int MultiExposure;

  @ushort()
  external int Quality;
}

final class libraw_ricoh_makernotes_t extends ffi.Struct {
  @ushort()
  external int AFStatus;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> AFAreaXPosition;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> AFAreaYPosition;

  @ushort()
  external int AFAreaMode;

  @ffi.UnsignedInt()
  external int SensorWidth;

  @ffi.UnsignedInt()
  external int SensorHeight;

  @ffi.UnsignedInt()
  external int CroppedImageWidth;

  @ffi.UnsignedInt()
  external int CroppedImageHeight;

  @ushort()
  external int WideAdapter;

  @ushort()
  external int CropMode;

  @ushort()
  external int NDFilter;

  @ushort()
  external int AutoBracketing;

  @ushort()
  external int MacroMode;

  @ushort()
  external int FlashMode;

  @ffi.Double()
  external double FlashExposureComp;

  @ffi.Double()
  external double ManualFlashOutput;
}

final class libraw_samsung_makernotes_t extends ffi.Struct {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.UnsignedInt> ImageSizeFull;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.UnsignedInt> ImageSizeCrop;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> ColorSpace;

  @ffi.Array.multi([11])
  external ffi.Array<ffi.UnsignedInt> key;

  @ffi.Double()
  external double DigitalGain;

  @ffi.Int()
  external int DeviceType;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> LensFirmware;
}

final class libraw_kodak_makernotes_t extends ffi.Struct {
  @ushort()
  external int BlackLevelTop;

  @ushort()
  external int BlackLevelBottom;

  @ffi.Short()
  external int offset_left;

  @ffi.Short()
  external int offset_top;

  @ushort()
  external int clipBlack;

  @ushort()
  external int clipWhite;

  @ffi.Array.multi([3, 3])
  external ffi.Array<ffi.Array<ffi.Float>> romm_camDaylight;

  @ffi.Array.multi([3, 3])
  external ffi.Array<ffi.Array<ffi.Float>> romm_camTungsten;

  @ffi.Array.multi([3, 3])
  external ffi.Array<ffi.Array<ffi.Float>> romm_camFluorescent;

  @ffi.Array.multi([3, 3])
  external ffi.Array<ffi.Array<ffi.Float>> romm_camFlash;

  @ffi.Array.multi([3, 3])
  external ffi.Array<ffi.Array<ffi.Float>> romm_camCustom;

  @ffi.Array.multi([3, 3])
  external ffi.Array<ffi.Array<ffi.Float>> romm_camAuto;

  @ushort()
  external int val018percent;

  @ushort()
  external int val100percent;

  @ushort()
  external int val170percent;

  @ffi.Short()
  external int MakerNoteKodak8a;

  @ffi.Float()
  external double ISOCalibrationGain;

  @ffi.Float()
  external double AnalogISO;
}

final class libraw_p1_makernotes_t extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> Software;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> SystemType;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> FirmwareString;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> SystemModel;
}

final class libraw_sony_info_t extends ffi.Struct {
  @ushort()
  external int CameraType;

  @uchar()
  external int Sony0x9400_version;

  @uchar()
  external int Sony0x9400_ReleaseMode2;

  @ffi.UnsignedInt()
  external int Sony0x9400_SequenceImageNumber;

  @uchar()
  external int Sony0x9400_SequenceLength1;

  @ffi.UnsignedInt()
  external int Sony0x9400_SequenceFileNumber;

  @uchar()
  external int Sony0x9400_SequenceLength2;

  @ffi.Uint8()
  external int AFAreaModeSetting;

  @ffi.Uint16()
  external int AFAreaMode;

  @ffi.Array.multi([2])
  external ffi.Array<ushort> FlexibleSpotPosition;

  @ffi.Uint8()
  external int AFPointSelected;

  @ffi.Uint8()
  external int AFPointSelected_0x201e;

  @ffi.Short()
  external int nAFPointsUsed;

  @ffi.Array.multi([10])
  external ffi.Array<ffi.Uint8> AFPointsUsed;

  @ffi.Uint8()
  external int AFTracking;

  @ffi.Uint8()
  external int AFType;

  @ffi.Array.multi([4])
  external ffi.Array<ushort> FocusLocation;

  @ushort()
  external int FocusPosition;

  @ffi.Int8()
  external int AFMicroAdjValue;

  @ffi.Int8()
  external int AFMicroAdjOn;

  @uchar()
  external int AFMicroAdjRegisteredLenses;

  @ushort()
  external int VariableLowPassFilter;

  @ffi.UnsignedInt()
  external int LongExposureNoiseReduction;

  @ushort()
  external int HighISONoiseReduction;

  @ffi.Array.multi([2])
  external ffi.Array<ushort> HDR;

  @ushort()
  external int group2010;

  @ushort()
  external int group9050;

  @ushort()
  external int len_group9050;

  @ushort()
  external int real_iso_offset;

  @ushort()
  external int MeteringMode_offset;

  @ushort()
  external int ExposureProgram_offset;

  @ushort()
  external int ReleaseMode2_offset;

  @ffi.UnsignedInt()
  external int MinoltaCamID;

  @ffi.Float()
  external double firmware;

  @ushort()
  external int ImageCount3_offset;

  @ffi.UnsignedInt()
  external int ImageCount3;

  @ffi.UnsignedInt()
  external int ElectronicFrontCurtainShutter;

  @ushort()
  external int MeteringMode2;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Char> SonyDateTime;

  @ffi.UnsignedInt()
  external int ShotNumberSincePowerUp;

  @ushort()
  external int PixelShiftGroupPrefix;

  @ffi.UnsignedInt()
  external int PixelShiftGroupID;

  @ffi.Char()
  external int nShotsInPixelShiftGroup;

  @ffi.Char()
  external int numInPixelShiftGroup;

  @ushort()
  external int prd_ImageHeight;

  @ushort()
  external int prd_ImageWidth;

  @ushort()
  external int prd_Total_bps;

  @ushort()
  external int prd_Active_bps;

  @ushort()
  external int prd_StorageMethod;

  @ushort()
  external int prd_BayerPattern;

  @ushort()
  external int SonyRawFileType;

  @ushort()
  external int RAWFileType;

  @ushort()
  external int RawSizeType;

  @ffi.UnsignedInt()
  external int Quality;

  @ushort()
  external int FileFormat;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> MetaVersion;

  @ffi.Float()
  external double AspectRatio;
}

final class libraw_colordata_t extends ffi.Struct {
  @ffi.Array.multi([65536])
  external ffi.Array<ushort> curve;

  @ffi.Array.multi([4104])
  external ffi.Array<ffi.UnsignedInt> cblack;

  @ffi.UnsignedInt()
  external int black;

  @ffi.UnsignedInt()
  external int data_maximum;

  @ffi.UnsignedInt()
  external int maximum;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.UnsignedInt> linear_max;

  @ffi.Float()
  external double fmaximum;

  @ffi.Float()
  external double fnorm;

  @ffi.Array.multi([8, 8])
  external ffi.Array<ffi.Array<ushort>> white;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> cam_mul;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> pre_mul;

  @ffi.Array.multi([3, 4])
  external ffi.Array<ffi.Array<ffi.Float>> cmatrix;

  @ffi.Array.multi([3, 4])
  external ffi.Array<ffi.Array<ffi.Float>> ccm;

  @ffi.Array.multi([3, 4])
  external ffi.Array<ffi.Array<ffi.Float>> rgb_cam;

  @ffi.Array.multi([4, 3])
  external ffi.Array<ffi.Array<ffi.Float>> cam_xyz;

  external ph1_t phase_one_data;

  @ffi.Float()
  external double flash_used;

  @ffi.Float()
  external double canon_ev;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> model2;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> UniqueCameraModel;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> LocalizedCameraModel;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> ImageUniqueID;

  @ffi.Array.multi([17])
  external ffi.Array<ffi.Char> RawDataUniqueID;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> OriginalRawFileName;

  external ffi.Pointer<ffi.Void> profile;

  @ffi.UnsignedInt()
  external int profile_length;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.UnsignedInt> black_stat;

  @ffi.Array.multi([2])
  external ffi.Array<libraw_dng_color_t> dng_color;

  external libraw_dng_levels_t dng_levels;

  @ffi.Array.multi([256, 4])
  external ffi.Array<ffi.Array<ffi.Int>> WB_Coeffs;

  @ffi.Array.multi([64, 5])
  external ffi.Array<ffi.Array<ffi.Float>> WBCT_Coeffs;

  @ffi.Int()
  external int as_shot_wb_applied;

  @ffi.Array.multi([2])
  external ffi.Array<libraw_P1_color_t> P1_color;

  @ffi.UnsignedInt()
  external int raw_bps;

  @ffi.Int()
  external int ExifColorSpace;
}

final class libraw_thumbnail_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int tformatAsInt;

  LibRaw_thumbnail_formats get tformat =>
      LibRaw_thumbnail_formats.fromValue(tformatAsInt);

  @ushort()
  external int twidth;

  @ushort()
  external int theight;

  @ffi.UnsignedInt()
  external int tlength;

  @ffi.Int()
  external int tcolors;

  external ffi.Pointer<ffi.Char> thumb;
}

final class libraw_thumbnail_item_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int tformatAsInt;

  LibRaw_internal_thumbnail_formats get tformat =>
      LibRaw_internal_thumbnail_formats.fromValue(tformatAsInt);

  @ushort()
  external int twidth;

  @ushort()
  external int theight;

  @ushort()
  external int tflip;

  @ffi.UnsignedInt()
  external int tlength;

  @ffi.UnsignedInt()
  external int tmisc;

  @INT64()
  external int toffset;
}

final class libraw_thumbnail_list_t extends ffi.Struct {
  @ffi.Int()
  external int thumbcount;

  @ffi.Array.multi([8])
  external ffi.Array<libraw_thumbnail_item_t> thumblist;
}

final class libraw_gps_info_t extends ffi.Struct {
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Float> latitude;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Float> longitude;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Float> gpstimestamp;

  @ffi.Float()
  external double altitude;

  @ffi.Char()
  external int altref;

  @ffi.Char()
  external int latref;

  @ffi.Char()
  external int longref;

  @ffi.Char()
  external int gpsstatus;

  @ffi.Char()
  external int gpsparsed;
}

typedef __time64_t = ffi.LongLong;
typedef Dart__time64_t = int;
typedef time_t = __time64_t;

final class libraw_imgother_t extends ffi.Struct {
  @ffi.Float()
  external double iso_speed;

  @ffi.Float()
  external double shutter;

  @ffi.Float()
  external double aperture;

  @ffi.Float()
  external double focal_len;

  @time_t()
  external int timestamp;

  @ffi.UnsignedInt()
  external int shot_order;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.UnsignedInt> gpsdata;

  external libraw_gps_info_t parsed_gps;

  @ffi.Array.multi([512])
  external ffi.Array<ffi.Char> desc;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> artist;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> analogbalance;
}

final class libraw_afinfo_item_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int AFInfoData_tag;

  @ffi.Short()
  external int AFInfoData_order;

  @ffi.UnsignedInt()
  external int AFInfoData_version;

  @ffi.UnsignedInt()
  external int AFInfoData_length;

  external ffi.Pointer<uchar> AFInfoData;
}

final class libraw_metadata_common_t extends ffi.Struct {
  @ffi.Float()
  external double FlashEC;

  @ffi.Float()
  external double FlashGN;

  @ffi.Float()
  external double CameraTemperature;

  @ffi.Float()
  external double SensorTemperature;

  @ffi.Float()
  external double SensorTemperature2;

  @ffi.Float()
  external double LensTemperature;

  @ffi.Float()
  external double AmbientTemperature;

  @ffi.Float()
  external double BatteryTemperature;

  @ffi.Float()
  external double exifAmbientTemperature;

  @ffi.Float()
  external double exifHumidity;

  @ffi.Float()
  external double exifPressure;

  @ffi.Float()
  external double exifWaterDepth;

  @ffi.Float()
  external double exifAcceleration;

  @ffi.Float()
  external double exifCameraElevationAngle;

  @ffi.Float()
  external double real_ISO;

  @ffi.Float()
  external double exifExposureIndex;

  @ushort()
  external int ColorSpace;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> firmware;

  @ffi.Float()
  external double ExposureCalibrationShift;

  @ffi.Array.multi([4])
  external ffi.Array<libraw_afinfo_item_t> afdata;

  @ffi.Int()
  external int afcount;
}

final class libraw_output_params_t extends ffi.Struct {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.UnsignedInt> greybox;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.UnsignedInt> cropbox;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Double> aber;

  @ffi.Array.multi([6])
  external ffi.Array<ffi.Double> gamm;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> user_mul;

  @ffi.Float()
  external double bright;

  @ffi.Float()
  external double threshold;

  @ffi.Int()
  external int half_size;

  @ffi.Int()
  external int four_color_rgb;

  @ffi.Int()
  external int highlight;

  @ffi.Int()
  external int use_auto_wb;

  @ffi.Int()
  external int use_camera_wb;

  @ffi.Int()
  external int use_camera_matrix;

  @ffi.Int()
  external int output_color;

  external ffi.Pointer<ffi.Char> output_profile;

  external ffi.Pointer<ffi.Char> camera_profile;

  external ffi.Pointer<ffi.Char> bad_pixels;

  external ffi.Pointer<ffi.Char> dark_frame;

  @ffi.Int()
  external int output_bps;

  @ffi.Int()
  external int output_tiff;

  @ffi.Int()
  external int output_flags;

  @ffi.Int()
  external int user_flip;

  @ffi.Int()
  external int user_qual;

  @ffi.Int()
  external int user_black;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Int> user_cblack;

  @ffi.Int()
  external int user_sat;

  @ffi.Int()
  external int med_passes;

  @ffi.Float()
  external double auto_bright_thr;

  @ffi.Float()
  external double adjust_maximum_thr;

  @ffi.Int()
  external int no_auto_bright;

  @ffi.Int()
  external int use_fuji_rotate;

  @ffi.Int()
  external int use_p1_correction;

  @ffi.Int()
  external int green_matching;

  @ffi.Int()
  external int dcb_iterations;

  @ffi.Int()
  external int dcb_enhance_fl;

  @ffi.Int()
  external int fbdd_noiserd;

  @ffi.Int()
  external int exp_correc;

  @ffi.Float()
  external double exp_shift;

  @ffi.Float()
  external double exp_preser;

  @ffi.Int()
  external int no_auto_scale;

  @ffi.Int()
  external int no_interpolation;
}

final class libraw_raw_unpack_params_t extends ffi.Struct {
  @ffi.Int()
  external int use_rawspeed;

  @ffi.Int()
  external int use_dngsdk;

  @ffi.UnsignedInt()
  external int options;

  @ffi.UnsignedInt()
  external int shot_select;

  @ffi.UnsignedInt()
  external int specials;

  @ffi.UnsignedInt()
  external int max_raw_memory_mb;

  @ffi.Int()
  external int sony_arw2_posterization_thr;

  @ffi.Float()
  external double coolscan_nef_gamma;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.Char> p4shot_order;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> custom_camera_strings;
}

final class libraw_rawdata_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> raw_alloc;

  external ffi.Pointer<ushort> raw_image;

  external ffi.Pointer<ffi.Pointer<ushort>> color4_image;

  external ffi.Pointer<ffi.Pointer<ushort>> color3_image;

  external ffi.Pointer<ffi.Float> float_image;

  external ffi.Pointer<ffi.Pointer<ffi.Float>> float3_image;

  external ffi.Pointer<ffi.Pointer<ffi.Float>> float4_image;

  external ffi.Pointer<ffi.Pointer<ffi.Short>> ph1_cblack;

  external ffi.Pointer<ffi.Pointer<ffi.Short>> ph1_rblack;

  external libraw_iparams_t iparams;

  external libraw_image_sizes_t sizes;

  external libraw_internal_output_params_t ioparams;

  external libraw_colordata_t color;
}

final class libraw_makernotes_lens_t extends ffi.Struct {
  @UINT64()
  external int LensID;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> Lens;

  @ushort()
  external int LensFormat;

  @ushort()
  external int LensMount;

  @UINT64()
  external int CamID;

  @ushort()
  external int CameraFormat;

  @ushort()
  external int CameraMount;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> body;

  @ffi.Short()
  external int FocalType;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> LensFeatures_pre;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> LensFeatures_suf;

  @ffi.Float()
  external double MinFocal;

  @ffi.Float()
  external double MaxFocal;

  @ffi.Float()
  external double MaxAp4MinFocal;

  @ffi.Float()
  external double MaxAp4MaxFocal;

  @ffi.Float()
  external double MinAp4MinFocal;

  @ffi.Float()
  external double MinAp4MaxFocal;

  @ffi.Float()
  external double MaxAp;

  @ffi.Float()
  external double MinAp;

  @ffi.Float()
  external double CurFocal;

  @ffi.Float()
  external double CurAp;

  @ffi.Float()
  external double MaxAp4CurFocal;

  @ffi.Float()
  external double MinAp4CurFocal;

  @ffi.Float()
  external double MinFocusDistance;

  @ffi.Float()
  external double FocusRangeIndex;

  @ffi.Float()
  external double LensFStops;

  @UINT64()
  external int TeleconverterID;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> Teleconverter;

  @UINT64()
  external int AdapterID;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> Adapter;

  @UINT64()
  external int AttachmentID;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> Attachment;

  @ushort()
  external int FocalUnits;

  @ffi.Float()
  external double FocalLengthIn35mmFormat;
}

final class libraw_nikonlens_t extends ffi.Struct {
  @ffi.Float()
  external double EffectiveMaxAp;

  @uchar()
  external int LensIDNumber;

  @uchar()
  external int LensFStops;

  @uchar()
  external int MCUVersion;

  @uchar()
  external int LensType;
}

final class libraw_dnglens_t extends ffi.Struct {
  @ffi.Float()
  external double MinFocal;

  @ffi.Float()
  external double MaxFocal;

  @ffi.Float()
  external double MaxAp4MinFocal;

  @ffi.Float()
  external double MaxAp4MaxFocal;
}

final class libraw_lensinfo_t extends ffi.Struct {
  @ffi.Float()
  external double MinFocal;

  @ffi.Float()
  external double MaxFocal;

  @ffi.Float()
  external double MaxAp4MinFocal;

  @ffi.Float()
  external double MaxAp4MaxFocal;

  @ffi.Float()
  external double EXIF_MaxAp;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> LensMake;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> Lens;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> LensSerial;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> InternalLensSerial;

  @ushort()
  external int FocalLengthIn35mmFormat;

  external libraw_nikonlens_t nikon;

  external libraw_dnglens_t dng;

  external libraw_makernotes_lens_t makernotes;
}

final class libraw_makernotes_t extends ffi.Struct {
  external libraw_canon_makernotes_t canon;

  external libraw_nikon_makernotes_t nikon;

  external libraw_hasselblad_makernotes_t hasselblad;

  external libraw_fuji_info_t fuji;

  external libraw_olympus_makernotes_t olympus;

  external libraw_sony_info_t sony;

  external libraw_kodak_makernotes_t kodak;

  external libraw_panasonic_makernotes_t panasonic;

  external libraw_pentax_makernotes_t pentax;

  external libraw_p1_makernotes_t phaseone;

  external libraw_ricoh_makernotes_t ricoh;

  external libraw_samsung_makernotes_t samsung;

  external libraw_metadata_common_t common;
}

final class libraw_shootinginfo_t extends ffi.Struct {
  @ffi.Short()
  external int DriveMode;

  @ffi.Short()
  external int FocusMode;

  @ffi.Short()
  external int MeteringMode;

  @ffi.Short()
  external int AFPoint;

  @ffi.Short()
  external int ExposureMode;

  @ffi.Short()
  external int ExposureProgram;

  @ffi.Short()
  external int ImageStabilization;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> BodySerial;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> InternalBodySerial;
}

final class libraw_custom_camera_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int fsize;

  @ushort()
  external int rw;

  @ushort()
  external int rh;

  @uchar()
  external int lm;

  @uchar()
  external int tm;

  @uchar()
  external int rm;

  @uchar()
  external int bm;

  @ushort()
  external int lf;

  @uchar()
  external int cf;

  @uchar()
  external int max;

  @uchar()
  external int flags;

  @ffi.Array.multi([10])
  external ffi.Array<ffi.Char> t_make;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Char> t_model;

  @ushort()
  external int offset;
}

final class libraw_data_t extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<ushort>> image;

  external libraw_image_sizes_t sizes;

  external libraw_iparams_t idata;

  external libraw_lensinfo_t lens;

  external libraw_makernotes_t makernotes;

  external libraw_shootinginfo_t shootinginfo;

  external libraw_output_params_t params;

  external libraw_raw_unpack_params_t rawparams;

  @ffi.UnsignedInt()
  external int progress_flags;

  @ffi.UnsignedInt()
  external int process_warnings;

  external libraw_colordata_t color;

  external libraw_imgother_t other;

  external libraw_thumbnail_t thumbnail;

  external libraw_thumbnail_list_t thumbs_list;

  external libraw_rawdata_t rawdata;

  external ffi.Pointer<ffi.Void> parent_class;
}

const double LIBRAW_DEFAULT_ADJUST_MAXIMUM_THRESHOLD = 0.75;

const double LIBRAW_DEFAULT_AUTO_BRIGHTNESS_THRESHOLD = 0.009999999776482582;

const int LIBRAW_MAX_ALLOC_MB_DEFAULT = 2048;

const int LIBRAW_MAX_PROFILE_SIZE_MB = 256;

const int LIBRAW_MAX_NONDNG_RAW_FILE_SIZE = 2147483647;

const int LIBRAW_MAX_CR3_RAW_FILE_SIZE = 2147483647;

const int LIBRAW_MAX_DNG_RAW_FILE_SIZE = 2147483647;

const int LIBRAW_MAX_THUMBNAIL_MB = 512;

const int LIBRAW_X3F_ALLOC_LIMIT_MB = 512;

const int LIBRAW_MAX_METADATA_BLOCKS = 1024;

const int LIBRAW_CBLACK_SIZE = 4104;

const int LIBRAW_IFD_MAXCOUNT = 10;

const int LIBRAW_THUMBNAIL_MAXCOUNT = 8;

const int LIBRAW_CRXTRACKS_MAXCOUNT = 16;

const int LIBRAW_AFDATA_MAXCOUNT = 4;

const int LIBRAW_AHD_TILE = 512;

const int LIBRAW_EXIFTOOLTAGTYPE_int8u = 1;

const int LIBRAW_EXIFTOOLTAGTYPE_string = 2;

const int LIBRAW_EXIFTOOLTAGTYPE_int16u = 3;

const int LIBRAW_EXIFTOOLTAGTYPE_int32u = 4;

const int LIBRAW_EXIFTOOLTAGTYPE_rational64u = 5;

const int LIBRAW_EXIFTOOLTAGTYPE_int8s = 6;

const int LIBRAW_EXIFTOOLTAGTYPE_undef = 7;

const int LIBRAW_EXIFTOOLTAGTYPE_binary = 7;

const int LIBRAW_EXIFTOOLTAGTYPE_int16s = 8;

const int LIBRAW_EXIFTOOLTAGTYPE_int32s = 9;

const int LIBRAW_EXIFTOOLTAGTYPE_rational64s = 10;

const int LIBRAW_EXIFTOOLTAGTYPE_float = 11;

const int LIBRAW_EXIFTOOLTAGTYPE_double = 12;

const int LIBRAW_EXIFTOOLTAGTYPE_ifd = 13;

const int LIBRAW_EXIFTOOLTAGTYPE_unicode = 14;

const int LIBRAW_EXIFTOOLTAGTYPE_complex = 15;

const int LIBRAW_EXIFTOOLTAGTYPE_int64u = 16;

const int LIBRAW_EXIFTOOLTAGTYPE_int64s = 17;

const int LIBRAW_EXIFTOOLTAGTYPE_ifd64 = 18;

const int LIBRAW_LENS_NOT_SET = -1;

const int LIBRAW_XTRANS = 9;

const int LIBRAW_PROGRESS_THUMB_MASK = 268435455;

const int LIBRAW_MAJOR_VERSION = 0;

const int LIBRAW_MINOR_VERSION = 22;

const int LIBRAW_PATCH_VERSION = 0;

const int LIBRAW_SHLIB_CURRENT = 26;

const int LIBRAW_SHLIB_REVISION = 0;

const int LIBRAW_SHLIB_AGE = 0;

const String LIBRAW_VERSION_STR = '0.22.0-Release';

const int LIBRAW_VERSION = 5632;

const int LibRawBigEndian = 0;
